import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { copyFileSync, mkdirSync, existsSync, watch, writeFileSync } from "fs";
import { resolve } from "path";
import {
	createInlineSqliteAssetsPlugin,
	resolveSqlitePackageAssets,
	verifyInlineSqliteBundle,
} from "./scripts/sqlite-inline-build.mjs";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");
const outdir = prod ? "./" : "test-vault/.obsidian/plugins/crosswalker/";
const sqliteAssets = resolveSqlitePackageAssets();
const sqliteMetafilePath = resolve("node_modules/.cache/crosswalker/sqlite-build-metafile.json");

if (!prod && !existsSync(outdir)) {
	mkdirSync(outdir, { recursive: true });
}

const verifyInlineSqlitePlugin = {
	name: "crosswalker-verify-inline-sqlite",
	setup(build) {
		build.onEnd((result) => {
			if (result.errors.length > 0) return;
			try {
				if (!result.metafile) throw new Error("esbuild did not return the required metafile");
				mkdirSync(resolve("node_modules/.cache/crosswalker"), { recursive: true });
				writeFileSync(sqliteMetafilePath, JSON.stringify(result.metafile, null, 2));
				verifyInlineSqliteBundle({
					bundlePath: resolve(outdir, "main.js"),
					metafile: result.metafile,
					assets: sqliteAssets,
				});
			} catch (error) {
				return {
					errors: [{
						text: error instanceof Error ? error.message : String(error),
					}],
				};
			}
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	loader: { '.tsv': 'text' },
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	// es2020 required for BigInt literals used by sqlite-vec-wasm-demo
	// (Obsidian's renderer is Chromium-based; ES2020 is safe everywhere
	// Obsidian runs — desktop Electron + mobile Capacitor WebView)
	target: "es2020",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outdir: outdir,
	metafile: true,
	plugins: [
		createInlineSqliteAssetsPlugin(sqliteAssets),
		verifyInlineSqlitePlugin,
	],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	copyFileSync("manifest.json", outdir + "manifest.json");
	copyFileSync("styles.css", outdir + "styles.css");
	await context.watch();

	// esbuild only watches the JS bundle's import graph — styles.css and
	// manifest.json are copied once above and would otherwise go stale mid-watch
	// (the 2026-06-13 "new markup, no styling" bug). Watch them too.
	for (const asset of ["styles.css", "manifest.json"]) {
		watch(asset, () => {
			try {
				copyFileSync(asset, outdir + asset);
				console.log(`[crosswalker] re-copied ${asset}`);
			} catch (e) {
				console.warn(`[crosswalker] failed to copy ${asset}: ${e.message}`);
			}
		});
	}

	console.log("Watching for changes (incl. styles.css + manifest.json + inline sqlite assets)...");
}
