/**
 * legacy-vault-refresh.test.ts -- the acceptance criterion for the per-import
 * destination root (2026-08-29).
 *
 * THE SCENARIO THIS FILE EXISTS FOR
 *
 * A user imported a source before the per-import root rule ran. Their notes sit
 * flat in the shared output folder ("Ontologies"), and their provenance records
 * `{id, scheme}` and no destination, because nothing recorded one yet. They now
 * refresh that import with a build where the per-import root rule DOES run, and
 * the derived default names a folder their notes have never been in
 * ("Ontologies/attack-mini").
 *
 * Nothing in that chain moves the existing import. It writes a SECOND copy of it
 * beside the first, reports paths the user has never seen, strands hubs at the
 * old address under identities nothing will claim again, and -- once two files
 * claim one curie -- raises "Ambiguous identity", which suppresses orphan
 * reporting for the entire run and surfaces to the user as "N rows failed" for
 * something that is not a row.
 *
 * WHAT IS ASSERTED
 *
 * The refresh must produce, under BOTH overwrite modes:
 *   - zero duplicate curies (no two files claiming one identity)
 *   - zero unsolicited moves of the user's existing notes
 *   - zero new orphans
 *   - no "Ambiguous identity" error
 *   - reported paths that actually exist
 *
 * The destination is not hard-coded into the refresh: it is read back out of a
 * real ImportFlow, because "where does this refresh land" is the decision the
 * whole failure hangs on. Pre-fix that accessor answers "Ontologies/attack-mini"
 * and every assertion below fails; the answer it must give is "Ontologies".
 *
 * ONE CLAUSE DOES NOT HOLD UNDER `skip`, AND IS MARKED `it.failing` RATHER THAN
 * SOFTENED -- see the `known gap` block below section 2.
 *
 * WHY THE PRE-FIX VAULT IS BUILT BY DE-MIGRATION
 *
 * The seed is generated by the current engine and then rewritten INTO the older
 * on-disk shape (destination stamp removed, hub curies returned to their
 * address-derived form). That is more faithful than hand-writing notes: every
 * byte except the two deliberate differences is exactly what a real vault holds,
 * so the test cannot pass by seeding something the engine would never produce.
 * The legacy hub-curie forms used here are the ones this repo's own test-vault
 * still carries (`shape-workbench:hub/frameworks`,
 * `shape-workbench:hub/frameworks/mitre-att-ck`), written by an earlier build.
 */

import { TFile, TFolder } from 'obsidian';
import {
	buildConfigFromWizardState,
	generateNotes,
	plannedConceptCuries,
} from '../src/generation/generation-engine';
import { ImportFlow, resolveDestinationDefault } from '../src/import/import-wizard';
import { DEFAULT_SETTINGS } from '../src/settings/settings-data';
import type { GenerationOptions } from '../src/generation/generation-engine';
import type { Recipe } from '../src/render';
import type { GenerationResult, ImportRecipe, ParsedData } from '../src/types/config';

// eslint-disable-next-line @typescript-eslint/no-var-requires
const yaml = require('js-yaml') as { load: (s: string) => unknown };

/** The shared output folder a pre-fix import landed in. */
const SHARED_ROOT = 'Ontologies';
/** What the per-import root rule derives for this source, and must NOT use here. */
const DERIVED_ROOT = 'Ontologies/attack-mini';
const SOURCE_FILE = 'attack-mini.csv';

// ---------------------------------------------------------------------------
// A stateful in-memory vault. Same shape as tests/enrichment-reimport.test.ts,
// plus `coldPaths`: files Obsidian has not indexed yet, whose metadata cache
// answers null and whose frontmatter is only reachable by reading the file.
// ---------------------------------------------------------------------------

function makeVault() {
	const files = new Map<string, string>();
	const folders = new Set<string>(['']);
	const coldPaths = new Set<string>();

	const getAbstractFileByPath = (path: string) => {
		if (files.has(path)) return new TFile(path);
		if (folders.has(path)) return new TFolder(path);
		return null;
	};
	const rename = jest.fn(async (file: { path: string }, newPath: string) => {
		const content = files.get(file.path);
		if (content === undefined) throw new Error(`Missing source file: ${file.path}`);
		files.delete(file.path);
		files.set(newPath, content);
		if (coldPaths.delete(file.path)) coldPaths.add(newPath);
		file.path = newPath;
	});
	const app = {
		vault: {
			getMarkdownFiles: () => [...files.keys()].map((path) => new TFile(path)),
			getAbstractFileByPath,
			create: async (path: string, content: string) => {
				files.set(path, content);
				return new TFile(path);
			},
			modify: async (file: { path: string }, content: string) => {
				files.set(file.path, content);
			},
			read: async (file: { path: string }) => files.get(file.path) ?? '',
			cachedRead: async (file: { path: string }) => files.get(file.path) ?? '',
			createFolder: async (path: string) => { folders.add(path); },
			rename,
			delete: async (file: { path: string }) => { files.delete(file.path); },
		},
		fileManager: { renameFile: rename },
		metadataCache: {
			getFileCache: (file: { path: string }) => {
				if (coldPaths.has(file.path)) return null;
				const text = files.get(file.path);
				if (!text) return null;
				const m = /^---\n([\s\S]*?)\n---/.exec(text.replace(/\r\n/g, '\n'));
				if (!m) return { frontmatter: {} };
				return { frontmatter: (yaml.load(m[1]) as Record<string, unknown>) ?? {} };
			},
		},
	};
	return { app: app as any, files, folders, coldPaths, rename };
}

// ---------------------------------------------------------------------------
// The import: a two-level layout (a folder per tactic, a file per technique)
// with level hubs on, which is what the shipped `browsable-framework` preset
// turns on. Hubs are the half of the vault that reconciled by ADDRESS only.
// ---------------------------------------------------------------------------

const ROWS = [
	{ id: 'T1078', tactic: 'Persistence', domain: 'Enterprise' },
	{ id: 'T1098', tactic: 'Persistence', domain: 'Enterprise' },
	{ id: 'T1595', tactic: 'Discovery', domain: 'Enterprise' },
	{ id: 'T1590', tactic: 'Discovery', domain: 'Enterprise' },
];

const COLUMNS = ['id', 'tactic', 'domain'];

function parsed(): ParsedData {
	return { columns: [...COLUMNS], rows: ROWS.map((r) => ({ ...r })), rowCount: ROWS.length };
}

/** Exactly what a user's Step-2 choices produce. */
const COLUMN_CONFIGS = new Map<string, { useAs: string; outputKey: string }>([
	['id', { useAs: 'title', outputKey: 'id' }],
	['tactic', { useAs: 'frontmatter', outputKey: 'tactic' }],
	['domain', { useAs: 'frontmatter', outputKey: 'domain' }],
]);

/**
 * The wizard's own config, built by the wizard's own helper. Not hand-written:
 * the whole point of the destination probe is that it derives the SAME curies
 * the write loop does, and a hand-written config could drift from either.
 *
 * No `name`, so the legacy shim names the ontology 'unknown' -- what a plain
 * unnamed wizard config really produces, on both the probe and the write path.
 */
const CONFIG: Partial<ImportRecipe> = buildConfigFromWizardState(COLUMN_CONFIGS, COLUMNS);

/** No `source`, so `ontologyId` falls through to the config name on both paths. */
const RECIPE: Recipe = {
	recipe: 'attack-mini',
	target: {
		layout: [
			{ level: 'tactic', mechanism: 'folder', template: '{tactic}' },
			{ level: 'leaf', mechanism: 'file', template: '{id}.md' },
		],
		enrichment: { children_lists: true, facet_notes: 'none', parent_note: 'sibling', level_hubs: 'notes' },
	},
};

/** The same import with FACET hubs instead of level hubs -- see section 3. */
const FACET_RECIPE: Recipe = {
	...RECIPE,
	target: {
		...RECIPE.target,
		enrichment: { children_lists: true, facet_notes: 'notes', parent_note: 'sibling', level_hubs: 'none' },
	},
};

function options(
	basePath: string,
	overwriteMode: 'skip' | 'replace',
	recipeOverride: Recipe = RECIPE,
): GenerationOptions {
	return {
		basePath,
		overwriteMode,
		createFolders: true,
		recipeOverride,
		sourceFileName: SOURCE_FILE,
		facetsForRow: (row: Record<string, unknown>) => [{ namespace: 'domain', value: String(row.domain) }],
	};
}

// ---------------------------------------------------------------------------
// Seeding a PRE-FIX vault.
// ---------------------------------------------------------------------------

/** Frontmatter of one note, as the vault currently holds it. */
function frontmatterOf(text: string): Record<string, unknown> {
	const m = /^---\n([\s\S]*?)\n---/.exec(text.replace(/\r\n/g, '\n'));
	return m ? ((yaml.load(m[1]) as Record<string, unknown>) ?? {}) : {};
}

/**
 * Rewrite a freshly generated vault into the shape a pre-fix build left behind:
 *   1. no `destination` in the import-set provenance (nothing recorded one)
 *   2. level-hub curies derived from the hub's FULL vault path, not from its
 *      path relative to the import root
 * Facet-hub curies are untouched: they never encoded an address.
 */
function deMigrateToPreFix(files: Map<string, string>, root: string): void {
	const rootLocalPart = root.split('/').map((s) => s.toLowerCase().replace(/[^a-z0-9-]+/g, '-')).join('/');
	for (const [path, text] of [...files]) {
		let out = text.replace(/\n[ \t]*destination: [^\n]*/g, '');
		// Order matters: the non-root form is rewritten first, so the root form's
		// replacement result is not then prefixed a second time.
		out = out.replace(/([a-z0-9_-]+):hub\/(?!_root\b)([^"'\s]+)/g, `$1:hub/${rootLocalPart}/$2`);
		out = out.replace(/([a-z0-9_-]+):hub\/_root\b/g, `$1:hub/${rootLocalPart}`);
		files.set(path, out);
	}
}

/** A vault holding one complete import, generated by the current engine. */
async function seedVault(recipeOverride: Recipe = RECIPE) {
	const vault = makeVault();
	const seed = await generateNotes(vault.app, parsed(), CONFIG, options(SHARED_ROOT, 'replace', recipeOverride));
	if (seed.errors.length > 0) throw new Error(`seed failed: ${JSON.stringify(seed.errors)}`);
	return vault;
}

/** The same vault, rewritten into the shape a pre-fix build left behind. */
async function seedPreFixVault(recipeOverride: Recipe = RECIPE) {
	const vault = await seedVault(recipeOverride);
	deMigrateToPreFix(vault.files, SHARED_ROOT);
	return vault;
}

// ---------------------------------------------------------------------------
// The wizard's answer to "where does this refresh land".
// ---------------------------------------------------------------------------

interface FlowInternals {
	currentOutputPath(): string;
	adoptExistingSetDestination(): Promise<boolean>;
	adoptionDeclined: string | null;
}

function makeFlow(app: unknown, opts: { globalRoot?: string; sourceFileName?: string } = {}): ImportFlow {
	const plugin = {
		settings: { ...DEFAULT_SETTINGS, defaultOutputPath: opts.globalRoot ?? SHARED_ROOT },
		debug: { info() {}, trace() {}, warn() {}, error() {} },
	} as unknown as ConstructorParameters<typeof ImportFlow>[1];
	const flow = new ImportFlow(
		app as ConstructorParameters<typeof ImportFlow>[0],
		plugin,
		{ containerEl: null as unknown as HTMLElement, close: () => {} },
	);
	flow.sourceFile = { name: opts.sourceFileName ?? SOURCE_FILE } as File;
	flow.parsedData = parsed();
	flow.columnConfigs = new Map(COLUMN_CONFIGS);
	return flow;
}

/** Where this flow says the import lands, after it has been allowed to look. */
async function askWhereItLands(app: unknown, opts?: { globalRoot?: string; sourceFileName?: string }) {
	const flow = makeFlow(app, opts);
	const inner = flow as unknown as FlowInternals;
	await inner.adoptExistingSetDestination();
	return { destination: inner.currentOutputPath(), declined: inner.adoptionDeclined };
}

// ---------------------------------------------------------------------------
// The audit the acceptance criterion is written in terms of.
// ---------------------------------------------------------------------------

/** curie -> every file claiming it. More than one entry is a duplicate identity. */
function curieOwners(files: Map<string, string>): Map<string, string[]> {
	const owners = new Map<string, string[]>();
	for (const [path, text] of files) {
		const fm = frontmatterOf(text);
		if (!fm._crosswalker || typeof fm.curie !== 'string') continue;
		const list = owners.get(fm.curie);
		if (list) list.push(path);
		else owners.set(fm.curie, [path]);
	}
	return owners;
}

function duplicateCuries(files: Map<string, string>): Array<[string, string[]]> {
	return [...curieOwners(files)].filter(([, paths]) => paths.length > 1);
}

function ambiguousIdentityErrors(result: GenerationResult): string[] {
	return result.errors.filter((e) => /Ambiguous identity/.test(e.message)).map((e) => e.message);
}

/** Every path the result reports back to the user, in one list. */
function reportedPaths(result: GenerationResult): string[] {
	return [
		...result.created,
		...result.skipped,
		...(result.moved ?? []).map((m) => m.to),
		...(result.orphans ?? []).map((o) => o.path),
	];
}

function pathsOfKind(files: Map<string, string>, kind: string): string[] {
	return [...files]
		.filter(([, text]) => frontmatterOf(text).kind === kind)
		.map(([path]) => path)
		.sort();
}

// ===========================================================================
// 1. Where a refresh of a pre-fix vault lands (F-1, F-2, F-3).
// ===========================================================================

describe('a refresh of a pre-fix import is offered the folder its notes are already in', () => {
	it('adopts the existing set root instead of the derived per-import root', async () => {
		const vault = await seedPreFixVault();

		// What the derived rule would say, spelled out so the failure this test
		// guards is legible: a folder the user's notes have never been in.
		expect(resolveDestinationDefault(SHARED_ROOT, SOURCE_FILE, null)).toBe(DERIVED_ROOT);

		const { destination, declined } = await askWhereItLands(vault.app);
		expect(destination).toBe(SHARED_ROOT);
		expect(destination).not.toBe(DERIVED_ROOT);
		expect(declined).toBeNull();
	});

	it('adopts the same root when the source file was renamed since the first import', async () => {
		// The case a pure "the same source name resolves to the same folder" rule
		// cannot cover: the derived root is a function of the file name, and the
		// file name is the one thing a user is free to change between releases.
		const vault = await seedPreFixVault();
		const { destination } = await askWhereItLands(vault.app, { sourceFileName: 'attack-mini-v2.csv' });
		expect(destination).toBe(SHARED_ROOT);
	});

	it('finds the set even when the vault has not been indexed yet (F-7)', async () => {
		// A cold metadata cache means "not indexed yet", never "absent". Treating
		// lag as absence here reports a genuinely new import and mints a second
		// copy of one the vault already holds.
		const vault = await seedPreFixVault();
		for (const path of vault.files.keys()) vault.coldPaths.add(path);
		const { destination } = await askWhereItLands(vault.app);
		expect(destination).toBe(SHARED_ROOT);
	});

	it('derives a fresh root for a source whose concepts the vault has never held', async () => {
		// Adoption must not degrade into "reuse whatever is already there": an
		// unrelated second import in the same vault is exactly what the per-import
		// root rule was restored for.
		const vault = await seedPreFixVault();
		const flow = makeFlow(vault.app, { sourceFileName: 'cis-controls-v8.csv' });
		flow.parsedData = { columns: [...COLUMNS], rows: [{ id: 'CIS-1', tactic: 'Inventory', domain: 'IG1' }], rowCount: 1 };
		const inner = flow as unknown as FlowInternals;
		await inner.adoptExistingSetDestination();
		expect(inner.currentOutputPath()).toBe('Ontologies/cis-controls-v8');
	});

	it('leaves the destination alone, and says why, when the set has no shared root', async () => {
		// Fail closed. One note dragged to the vault root collapses the recovered
		// prefix, and inventing a root there would move the user's whole import.
		const vault = await seedPreFixVault();
		const stray = [...vault.files.keys()].find((p) => p.endsWith('T1078.md'))!;
		vault.files.set('T1078.md', vault.files.get(stray)!);
		vault.files.delete(stray);

		const { destination, declined } = await askWhereItLands(vault.app);
		expect(destination).toBe(DERIVED_ROOT); // unchanged: the derived default
		expect(declined).toMatch(/do not share one folder/);
		expect(declined).toContain('T1078.md');
	});

	it('probes the identities the write loop will actually produce', async () => {
		// The probe and the write loop must derive the same curie, or adoption is
		// answering a question about a different import. Asserted against the
		// curies a real generation run wrote, not against a literal.
		const vault = await seedPreFixVault();
		const written = [...vault.files.values()]
			.map((text) => frontmatterOf(text).curie)
			.filter((c): c is string => typeof c === 'string' && !c.includes(':hub/'))
			.sort();
		const probed = plannedConceptCuries(CONFIG.mapping!, 'unknown', ROWS, 100).sort();
		expect(probed).toEqual(written);
	});
});

// ===========================================================================
// 2. THE ACCEPTANCE CRITERION.
//
// KNOWN GAP -- `skip` mode, two clauses, marked `it.failing` below.
//
// Under `overwriteMode: 'skip'` every row returns from the write loop BEFORE
// `enrichRecords.push` (generation-engine.ts: the skip `return` sits above the
// collection), so the enrichment batch is empty, `applyEnrichment` never runs,
// and no hub curie is ever added to `producedCuries`. Every hub the set owns is
// therefore reported as an orphan, and no hub is reconciled or restamped.
//
// That is NOT caused by the per-import root work: the `does not depend on the
// legacy shape` test immediately below reproduces it on a vault generated by the
// current engine and never de-migrated. It is pinned with `it.failing` rather
// than softened, so a fix to skip-mode enrichment turns this suite red until the
// expectation is restored.
// ===========================================================================

describe.each(['replace', 'skip'] as const)('refreshing a pre-fix vault (overwriteMode %s)', (overwriteMode) => {
	/** Clauses the skip-mode enrichment gap above prevents from holding. */
	const clause = overwriteMode === 'skip' ? it.failing : it;

	async function refresh() {
		const vault = await seedPreFixVault();
		const before = new Map(vault.files);
		const { destination } = await askWhereItLands(vault.app);
		const result = await generateNotes(vault.app, parsed(), CONFIG, options(destination, overwriteMode));
		return { vault, before, destination, result };
	}

	it('writes into the folder the set already occupies', async () => {
		const { destination } = await refresh();
		expect(destination).toBe(SHARED_ROOT);
	});

	it('leaves no two files claiming one identity', async () => {
		const { vault } = await refresh();
		expect(duplicateCuries(vault.files)).toEqual([]);
	});

	it('raises no ambiguous-identity error', async () => {
		const { result } = await refresh();
		expect(ambiguousIdentityErrors(result)).toEqual([]);
		expect(result.errors).toEqual([]);
	});

	it('moves none of the user existing notes', async () => {
		const { vault, before, result } = await refresh();
		expect(result.moved ?? []).toEqual([]);
		// Not just "reported no moves": every note the user had is still where it was.
		for (const path of before.keys()) expect(vault.files.has(path)).toBe(true);
	});

	it('creates no second copy of the import', async () => {
		const { vault, before } = await refresh();
		expect([...vault.files.keys()].sort()).toEqual([...before.keys()].sort());
	});

	it('reports only paths that exist', async () => {
		const { vault, result } = await refresh();
		const missing = reportedPaths(result).filter((p) => !vault.files.has(p));
		expect(missing).toEqual([]);
	});

	clause('reports no new orphans', async () => {
		const { result } = await refresh();
		expect(result.orphans ?? []).toEqual([]);
	});

	clause('leaves every hub holding exactly one identity, restamped to the address-independent form', async () => {
		const { vault } = await refresh();
		expect(pathsOfKind(vault.files, 'hub')).toEqual([
			'Ontologies/Discovery/Discovery.md',
			'Ontologies/Ontologies.md',
			'Ontologies/Persistence/Persistence.md',
		]);
		const hubCuries = [...vault.files.values()]
			.filter((text) => frontmatterOf(text).kind === 'hub')
			.map((text) => frontmatterOf(text).curie)
			.sort();
		expect(hubCuries).toEqual(['unknown:hub/_root', 'unknown:hub/discovery', 'unknown:hub/persistence']);
	});
});

describe('the skip-mode hub gap does not depend on the legacy shape', () => {
	it('orphans every hub even on a vault this engine generated moments earlier', async () => {
		// The isolating experiment. No de-migration, no destination change, no
		// legacy curies: the only variable is overwriteMode. If this ever goes
		// green, the two `it.failing` clauses above must be un-marked in the same
		// change.
		const vault = await seedVault();
		const result = await generateNotes(vault.app, parsed(), CONFIG, options(SHARED_ROOT, 'skip'));
		expect((result.orphans ?? []).map((o) => o.curie).sort()).toEqual([
			'unknown:hub/_root',
			'unknown:hub/discovery',
			'unknown:hub/persistence',
		]);
	});

	it('does not orphan them under replace, which is the same vault and the same run', async () => {
		const vault = await seedVault();
		const result = await generateNotes(vault.app, parsed(), CONFIG, options(SHARED_ROOT, 'replace'));
		expect(result.orphans ?? []).toEqual([]);
	});
});

// ===========================================================================
// 3. The safety net: what happens when the destination really does change.
//
// F-3 is what keeps the destination still in section 2, but it declines on
// purpose in several real situations (a streamed source has no eager rows to
// probe; a source above the probe ceiling; several sets claiming the same
// identities; notes that share no root). What a moved destination does to hubs
// therefore still matters.
//
// The two hub kinds diverge here, and the divergence is the boundary of the fix:
//
//   FACET hubs carry an address-independent curie (`<ont>:facet/<ns>/<value>`),
//   so identity resolution finds them wherever they sit and RELOCATES them.
//   That is F-6 doing real work: before it, the path-only lookup missed and a
//   second facet hub was created, permanently claiming the same curie.
//
//   LEVEL hubs carry a curie relative to the import root (F-4), which is the
//   right rule -- but when the root itself moves, the old hub is a hub for a
//   folder this import no longer produces, and no alias can match it. The old
//   level hubs are left behind. Asserted, named, and left to F-3 to keep out of
//   reach rather than quietly implied to be fixed.
// ===========================================================================

describe('a moved destination relocates facet hubs instead of duplicating them (F-6)', () => {
	async function movedFacetRefresh() {
		const vault = await seedPreFixVault(FACET_RECIPE);
		const before = new Map(vault.files);
		const result = await generateNotes(vault.app, parsed(), CONFIG, options(DERIVED_ROOT, 'replace', FACET_RECIPE));
		return { vault, before, result };
	}

	it('leaves exactly one note claiming the facet identity', async () => {
		const { vault, result } = await movedFacetRefresh();
		expect(ambiguousIdentityErrors(result)).toEqual([]);
		expect(duplicateCuries(vault.files)).toEqual([]);
		expect(pathsOfKind(vault.files, 'facet')).toEqual([`${DERIVED_ROOT}/Enterprise.md`]);
		expect(vault.files.has(`${SHARED_ROOT}/Enterprise.md`)).toBe(false);
	});

	it('reports the relocation, so a rearranged vault is never a mystery', async () => {
		const { result } = await movedFacetRefresh();
		expect((result.moved ?? []).map((m) => `${m.from} -> ${m.to}`))
			.toContain(`${SHARED_ROOT}/Enterprise.md -> ${DERIVED_ROOT}/Enterprise.md`);
	});

	it('carries the user prose on that hub across with it', async () => {
		// The reason a hub is moved rather than regenerated at the new address and
		// deleted at the old: a hub can hold content only the user has.
		const vault = await seedPreFixVault(FACET_RECIPE);
		const hubPath = `${SHARED_ROOT}/Enterprise.md`;
		vault.files.set(hubPath, `${vault.files.get(hubPath)!}\nMy own notes about this facet.\n`);

		await generateNotes(vault.app, parsed(), CONFIG, options(DERIVED_ROOT, 'replace', FACET_RECIPE));

		expect(vault.files.get(`${DERIVED_ROOT}/Enterprise.md`)).toContain('My own notes about this facet.');
	});

	it('refuses to relocate onto an occupied address, and says so', async () => {
		// Refusing to move is always safe; clobbering a note this run did not
		// produce is not.
		const vault = await seedPreFixVault(FACET_RECIPE);
		vault.folders.add(DERIVED_ROOT);
		vault.files.set(`${DERIVED_ROOT}/Enterprise.md`, '# Something a user already put here\n');

		const result = await generateNotes(vault.app, parsed(), CONFIG, options(DERIVED_ROOT, 'replace', FACET_RECIPE));

		expect(vault.files.get(`${DERIVED_ROOT}/Enterprise.md`)).toContain('Something a user already put here');
		expect((result.warnings ?? []).map((w) => w.message).join('\n')).toMatch(/already occupied/);
	});
});

describe('a moved destination still strands level hubs (the residual F-3 protects against)', () => {
	it('leaves the old level hubs behind, because their identity is relative to a root that moved', async () => {
		const vault = await seedPreFixVault();
		const result = await generateNotes(vault.app, parsed(), CONFIG, options(DERIVED_ROOT, 'replace'));

		// No duplicate identity and no ambiguity: the two generations of hub carry
		// DIFFERENT curies, which is precisely why neither can see the other.
		expect(ambiguousIdentityErrors(result)).toEqual([]);
		expect(duplicateCuries(vault.files)).toEqual([]);

		expect(pathsOfKind(vault.files, 'hub')).toEqual([
			'Ontologies/Discovery/Discovery.md',
			'Ontologies/Ontologies.md',
			'Ontologies/Persistence/Persistence.md',
			`${DERIVED_ROOT}/Discovery/Discovery.md`,
			`${DERIVED_ROOT}/Persistence/Persistence.md`,
			`${DERIVED_ROOT}/attack-mini.md`,
		]);
	});

	it('relocates the concept notes by identity, so no concept is duplicated', async () => {
		// The concepts DO reconcile, because their curies never encoded an address.
		// This is what makes the level-hub residual survivable rather than fatal.
		const vault = await seedPreFixVault();
		const result = await generateNotes(vault.app, parsed(), CONFIG, options(DERIVED_ROOT, 'replace'));

		expect((result.moved ?? []).map((m) => m.to).sort()).toEqual([
			`${DERIVED_ROOT}/Discovery/T1590.md`,
			`${DERIVED_ROOT}/Discovery/T1595.md`,
			`${DERIVED_ROOT}/Persistence/T1078.md`,
			`${DERIVED_ROOT}/Persistence/T1098.md`,
		]);
		expect(vault.files.has(`${SHARED_ROOT}/Persistence/T1078.md`)).toBe(false);
	});
});
