/**
 * legacy-vault-refresh.test.ts -- the D1 Part A acceptance criterion (A-8).
 *
 * THE SCENARIO THIS FILE EXISTS FOR
 *
 * A user imported a source before the per-import root rule ran. Their notes and
 * their hubs sit in the shared output folder ("Ontologies") itself, and their
 * provenance records `{id, scheme}` and no destination, because nothing recorded
 * one yet. They now refresh that import with a build where the per-import root
 * rule DOES run, and the derived default names a folder their notes have never
 * been in ("Ontologies/attack-mini").
 *
 * Nothing in that chain moves the existing import. It writes a SECOND copy of it
 * beside the first, reports paths the user has never seen, strands hubs at the
 * old address under identities nothing will claim again, and -- once two files
 * claim one curie -- raises "Ambiguous identity", which suppresses orphan
 * reporting for the entire run and surfaces as "N rows failed" for something
 * that is not a row.
 *
 * PART A'S ANSWER, AND WHY THE TESTS ARE SHAPED THIS WAY
 *
 * A refresh never changes a set's root. The destination for a refresh IS the
 * set's existing root, resolved once from the notes the set already owns, and
 * ownership is decided by what the notes are STAMPED with (recipe id, ontology
 * prefix) rather than by which folder they happen to sit in. So the destination
 * is never hard-coded into the refresh below: it is read back out of a real
 * `ImportFlow` through the same accessor every write path uses, because "where
 * does this refresh land" is the decision the whole failure hangs on.
 *
 * WHY THE PRE-FIX VAULT IS BUILT BY DE-MIGRATION
 *
 * The seed is generated by the current engine and then rewritten INTO the older
 * on-disk shape (destination stamp removed, hub curies returned to their
 * address-derived form). That is more faithful than hand-writing notes: every
 * byte except the two deliberate differences is exactly what a real vault holds,
 * so the test cannot pass by seeding something the engine would never produce.
 *
 * WHAT IS ASSERTED, AND WHERE
 *
 *   1. Where a refresh lands, and which set it is attributed to (A-1 to A-3).
 *   2. The acceptance clauses themselves, under BOTH overwrite modes (A-8).
 *   3. A second, unrelated framework in the same legacy vault (A-8 companion).
 *   4. A cold metadata cache at step 3 (A-8 companion, A-4).
 *   5. Segment-wise root recovery and failing closed, at the wizard (A-3).
 *   6. The new-set occupancy guard and suppressed moves under skip (A-6).
 *   7. What the results screen renders (A-7).
 *   8. The isolating experiment that showed the skip-mode gap was not the
 *      destination rule's doing, now the control that it stays closed (AM-2).
 *   9. The same criterion driven end to end through two real wizard runs, in
 *      BOTH overwrite modes (A-8 restated).
 *  10. The classic import path, which stamps no ontology of its own (AM-1).
 *  11. What the success notice says on every run (AM-3).
 *  12. An identity collision on a run that would otherwise close (AM-4).
 *
 * THE THREE GAPS THIS FILE USED TO PIN WITH `it.failing`, AND WHERE THEY WENT
 *
 *   a. `skip` mode orphaned every hub and restamped none (section 2, isolated
 *      in section 8). Closed by AM-2: a row this run KEPT is still a row it
 *      vouches for, so the hubs those rows imply are marked produced without
 *      anything being rewritten. Both clauses are ordinary `it` again, and
 *      section 8 now asserts the absence rather than the presence.
 *   b. "and the orphan count" was invisible on a clean run, because the screen
 *      renders the orphan line only when the count is non-zero (section 7).
 *      Closed by AM-3, but NOT on the screen: a clean refresh never draws one.
 *      The counts ride on the success notice instead, on every run (section 11).
 *   c. A clean refresh closed the host instead of reporting anything (section
 *      9). Closed by AM-3 the same way: it still closes, and the user is still
 *      told both numbers, because the notice fires before the close.
 *
 * A regression in any of the three turns this suite red at the named section.
 */

import { TFile, TFolder } from 'obsidian';
import {
	buildConfigFromWizardState,
	generateFromRecipe,
	generateNotes,
} from '../src/generation/generation-engine';
import { discoverImportSets, type DiscoveredImportSet, type ImportSetOption } from '../src/generation/import-set';
import { ImportFlow, resolveDestinationDefault } from '../src/import/import-wizard';
// AM-1. Imported, never retyped: these are the placeholder identities the
// classic path mints, and a second copy of the literals in a test is a copy
// that can agree with a drifted implementation instead of catching it.
import {
	LEGACY_ONTOLOGY_SENTINEL,
	LEGACY_RECIPE_ID_SENTINEL,
} from '../src/generation/legacy-recipe-shim';
import { MappingWorkbench } from '../src/import/workbench';
import { analyzeColumns } from '../src/import/parsers/csv-parser';
import { DEFAULT_SETTINGS } from '../src/settings/settings-data';
import type { DebugLog } from '../src/utils/debug';
import type { GenerationOptions } from '../src/generation/generation-engine';
import type { Recipe } from '../src/render';
import type { GenerationResult, ImportRecipe, ParsedData } from '../src/types/config';

// eslint-disable-next-line @typescript-eslint/no-var-requires
const yaml = require('js-yaml') as { load: (s: string) => unknown };

// ---------------------------------------------------------------------------
// AM-3 / AM-4: what the user is TOLD.
//
// The moved and orphan counts ride on the SUCCESS NOTICE, not on the results
// screen, because the run A-8 is written about -- a clean refresh -- closes the
// wizard without ever drawing a screen. A test that only inspects rendered text
// therefore cannot see the guarantee at all.
//
// `require` rather than `import * as obsidian`: under esModuleInterop
// TypeScript copies a namespace import into a fresh object, so a spy installed
// on the copy would leave src/ calling the original and every assertion below
// would pass for the wrong reason. This is the same live module object that
// `import { Notice } from 'obsidian'` resolves to inside the wizard.
// ---------------------------------------------------------------------------
// eslint-disable-next-line @typescript-eslint/no-var-requires
const obsidianModule = require('obsidian') as {
	Notice: new (message: string, timeout?: number) => unknown;
};
const RealNotice = obsidianModule.Notice;

/** Every notice raised since the current test began, in order. */
const notices: string[] = [];

beforeAll(() => {
	obsidianModule.Notice = class {
		constructor(message: string) { notices.push(message); }
	} as unknown as typeof RealNotice;
});

afterAll(() => { obsidianModule.Notice = RealNotice; });

beforeEach(() => { notices.length = 0; });

/** All notice text as one string, so one assertion can read the whole report. */
const noticeText = (): string => notices.join('\n');

/** The shared output folder a pre-fix import landed in. */
const SHARED_ROOT = 'Ontologies';
/** What the per-import root rule derives for this source, and must NOT use here. */
const DERIVED_ROOT = 'Ontologies/attack-mini';
const SOURCE_FILE = 'attack-mini.csv';
/** The ontology this source stamps on every note it writes. */
const ONTOLOGY = 'attack-mini';

const debugStub = {
	info() {}, trace() {}, warn() {}, error() {},
	newTraceId: () => 'test-trace',
	withTrace: <T>(_id: string, fn: () => T): T => fn(),
} as unknown as DebugLog;

// ---------------------------------------------------------------------------
// A stateful in-memory vault. Same shape as tests/enrichment-reimport.test.ts,
// plus `coldPaths`: files Obsidian has not indexed yet, whose metadata cache
// answers null and whose frontmatter is only reachable by reading the file.
// ---------------------------------------------------------------------------

function makeVault() {
	const files = new Map<string, string>();
	const folders = new Set<string>(['']);
	const coldPaths = new Set<string>();

	const getAbstractFileByPath = (path: string) => {
		if (files.has(path)) return new TFile(path);
		if (folders.has(path)) return new TFolder(path);
		return null;
	};
	const rename = jest.fn(async (file: { path: string }, newPath: string) => {
		const content = files.get(file.path);
		if (content === undefined) throw new Error(`Missing source file: ${file.path}`);
		files.delete(file.path);
		files.set(newPath, content);
		if (coldPaths.delete(file.path)) coldPaths.add(newPath);
		file.path = newPath;
	});
	const createFolder = jest.fn(async (path: string) => { folders.add(path); });
	const create = jest.fn(async (path: string, content: string) => {
		files.set(path, content);
		return new TFile(path);
	});
	const modify = jest.fn(async (file: { path: string }, content: string) => {
		files.set(file.path, content);
	});
	const app = {
		vault: {
			getMarkdownFiles: () => [...files.keys()].map((path) => new TFile(path)),
			getAbstractFileByPath,
			create,
			modify,
			read: async (file: { path: string }) => files.get(file.path) ?? '',
			cachedRead: async (file: { path: string }) => files.get(file.path) ?? '',
			createFolder,
			rename,
			delete: async (file: { path: string }) => { files.delete(file.path); },
		},
		fileManager: { renameFile: rename },
		metadataCache: {
			getFileCache: (file: { path: string }) => {
				if (coldPaths.has(file.path)) return null;
				const text = files.get(file.path);
				if (!text) return null;
				const m = /^---\n([\s\S]*?)\n---/.exec(text.replace(/\r\n/g, '\n'));
				if (!m) return { frontmatter: {} };
				return { frontmatter: (yaml.load(m[1]) as Record<string, unknown>) ?? {} };
			},
			// `waitForMetadataResolve` subscribes to 'resolved' and races it against
			// its own timeout. Firing on the next tick keeps a cold-cache test at
			// milliseconds instead of the 4-second fallback, and proves the wizard
			// re-checks AFTER the wait rather than trusting that it returned.
			on: (_event: string, cb: () => void) => { setTimeout(cb, 0); return {}; },
			offref: () => {},
		},
	};
	return { app: app as any, files, folders, coldPaths, rename, createFolder, create, modify };
}

type Vault = ReturnType<typeof makeVault>;

/**
 * Forget the writes that BUILT the fixture, so "wrote nothing" means "wrote
 * nothing during the act under test". Seeding a pre-fix vault runs a real
 * generation, and its `create` calls are not evidence about the refresh.
 */
function forgetSeedWrites(vault: Vault): void {
	vault.create.mockClear();
	vault.modify.mockClear();
	vault.rename.mockClear();
	vault.createFolder.mockClear();
}

// ---------------------------------------------------------------------------
// The import: a two-level layout (a folder per tactic, a file per technique)
// with level hubs on, which is what the shipped `browsable-framework` preset
// turns on. Hubs are the half of the vault that reconciled by ADDRESS only.
// ---------------------------------------------------------------------------

const ROWS = [
	{ technique_id: 'T1078', name: 'Valid Accounts', tactic: 'Persistence', domain: 'Enterprise' },
	{ technique_id: 'T1078.001', name: 'Default Accounts', tactic: 'Persistence', domain: 'Enterprise' },
	{ technique_id: 'T1098', name: 'Account Manipulation', tactic: 'Persistence', domain: 'Enterprise' },
	{ technique_id: 'T1595', name: 'Active Scanning', tactic: 'Discovery', domain: 'Enterprise' },
	{ technique_id: 'T1595.002', name: 'Vulnerability Scanning', tactic: 'Discovery', domain: 'Enterprise' },
	{ technique_id: 'T1590', name: 'Gather Network Info', tactic: 'Discovery', domain: 'Enterprise' },
];

const COLUMNS = ['technique_id', 'name', 'tactic', 'domain'];

function parsed(): ParsedData {
	return { columns: [...COLUMNS], rows: ROWS.map((r) => ({ ...r })), rowCount: ROWS.length };
}

/** Exactly what a user's Step-2 choices produce. */
const COLUMN_CONFIGS = new Map<string, { useAs: string; outputKey: string }>([
	['technique_id', { useAs: 'title', outputKey: 'technique_id' }],
	['name', { useAs: 'frontmatter', outputKey: 'name' }],
	['tactic', { useAs: 'frontmatter', outputKey: 'tactic' }],
	['domain', { useAs: 'frontmatter', outputKey: 'domain' }],
]);

const CONFIG: Partial<ImportRecipe> = buildConfigFromWizardState(COLUMN_CONFIGS, COLUMNS);

/**
 * The recipe the pre-fix import was written with. `recipe` and `source.ontology`
 * are the two facts A-2 matches a source against, and they are spelled exactly
 * the way a workbench import spells them (`custom-<ontology-slug>` /
 * `<ontology-slug>`, recipe-document.ts createFreshRecipeDocument), so the vault
 * this seeds is one the shipped path could really have produced.
 */
const RECIPE: Recipe = {
	recipe: `custom-${ONTOLOGY}`,
	source: { ontology: ONTOLOGY, levels: ['tactic', 'leaf'] },
	target: {
		layout: [
			{ level: 'tactic', mechanism: 'folder', template: '{tactic}' },
			{ level: 'leaf', mechanism: 'file', template: '{technique_id}.md' },
		],
		enrichment: { children_lists: true, facet_notes: 'none', parent_note: 'sibling', level_hubs: 'notes' },
	},
};

/** The same import with FACET hubs instead of level hubs -- see section 6. */
const FACET_RECIPE: Recipe = {
	...RECIPE,
	target: {
		...RECIPE.target,
		enrichment: { children_lists: true, facet_notes: 'notes', parent_note: 'sibling', level_hubs: 'none' },
	},
};

function options(
	basePath: string,
	overwriteMode: 'skip' | 'replace',
	extra: {
		recipeOverride?: Recipe;
		importSet?: ImportSetOption;
	} = {},
): GenerationOptions {
	return {
		basePath,
		overwriteMode,
		createFolders: true,
		recipeOverride: extra.recipeOverride ?? RECIPE,
		sourceFileName: SOURCE_FILE,
		...(extra.importSet !== undefined ? { importSet: extra.importSet } : {}),
		facetsForRow: (row: Record<string, unknown>) => [{ namespace: 'domain', value: String(row.domain) }],
	};
}

// ---------------------------------------------------------------------------
// Seeding a PRE-FIX vault.
// ---------------------------------------------------------------------------

/** Frontmatter of one note, as the vault currently holds it. */
function frontmatterOf(text: string): Record<string, unknown> {
	const m = /^---\n([\s\S]*?)\n---/.exec(text.replace(/\r\n/g, '\n'));
	return m ? ((yaml.load(m[1]) as Record<string, unknown>) ?? {}) : {};
}

/**
 * Rewrite a freshly generated vault into the shape a pre-fix build left behind:
 *   1. no `destination` in the import-set provenance (nothing recorded one)
 *   2. level-hub curies derived from the hub's FULL vault path, not from its
 *      path relative to the import root
 * Facet-hub curies are untouched: they never encoded an address.
 */
function deMigrateToPreFix(files: Map<string, string>, root: string): void {
	const rootLocalPart = root.split('/').map((s) => s.toLowerCase().replace(/[^a-z0-9-]+/g, '-')).join('/');
	for (const [path, text] of [...files]) {
		let out = text.replace(/\n[ \t]*destination: [^\n]*/g, '');
		// Order matters: the non-root form is rewritten first, so the root form's
		// replacement result is not then prefixed a second time.
		out = out.replace(/([a-z0-9_-]+):hub\/(?!_root\b)([^"'\s]+)/g, `$1:hub/${rootLocalPart}/$2`);
		out = out.replace(/([a-z0-9_-]+):hub\/_root\b/g, `$1:hub/${rootLocalPart}`);
		files.set(path, out);
	}
}

/** A vault holding one complete import, generated by the current engine. */
async function seedVault(recipeOverride: Recipe = RECIPE, basePath: string = SHARED_ROOT) {
	const vault = makeVault();
	const seed = await generateNotes(vault.app, parsed(), CONFIG, options(basePath, 'replace', { recipeOverride }));
	if (seed.errors.length > 0) throw new Error(`seed failed: ${JSON.stringify(seed.errors)}`);
	return vault;
}

/** The same vault, rewritten into the shape a pre-fix build left behind. */
async function seedPreFixVault(recipeOverride: Recipe = RECIPE) {
	const vault = await seedVault(recipeOverride, SHARED_ROOT);
	deMigrateToPreFix(vault.files, SHARED_ROOT);
	return vault;
}

// ---------------------------------------------------------------------------
// The wizard's answer to "where does this refresh land, and what does it own".
// ---------------------------------------------------------------------------

/**
 * Private members the review screen, the destination breadcrumb and the generate
 * button all read. Reached through a cast for the same reason
 * destination-default.test.ts does it: the flow's DOM is not mountable under the
 * obsidian mock, and these ARE the decisions, not incidental internals.
 */
interface FlowInternals {
	currentOutputPath(): string;
	prepareStep3(force?: boolean): Promise<{ ok: boolean; changed: boolean }>;
	selectedImportSet(): ImportSetOption | undefined;
	validateImportSetSelection(): boolean;
	refreshRootProblem(): string | null;
	newSetOccupancyProblem(): string | null;
	sourceIdentityKeys(): { recipeId: string | null; ontologyPrefix: string | null };
	discoveredSets: DiscoveredImportSet[] | null;
	indexingBlocked: string | null;
	importSetChoice: ImportSetOption | null;
}

const inner = (flow: ImportFlow): FlowInternals => flow as unknown as FlowInternals;

/**
 * A stand-in container that absorbs the whole Obsidian element surface and
 * records the text of everything drawn into it.
 *
 * The wizard's DOM is not mountable under the obsidian mock, and hand-listing
 * the members `renderStep` touches is a guessing game that fails as an obscure
 * "is not a function" the day someone adds a class. A proxy that answers every
 * property with another element removes that whole failure mode, while the two
 * text-bearing calls -- `createEl(tag, { text })` and `setText` -- are captured,
 * which is what the assertions are actually about.
 */
function makeRecordingEl(texts: string[]): HTMLElement {
	const target = function () { /* elements are called for nothing; see apply */ };
	return new Proxy(target, {
		get(_t, prop) {
			// A thenable would make an element look like a promise to `await`.
			if (prop === 'then') return undefined;
			if (prop === 'setText') return (t: string) => { texts.push(t); };
			if (prop === 'createEl' || prop === 'createDiv' || prop === 'createSpan') {
				return (first?: unknown, second?: { text?: string }) => {
					const opts = (typeof first === 'object' ? first : second) as { text?: string } | undefined;
					if (opts?.text) texts.push(opts.text);
					return makeRecordingEl(texts);
				};
			}
			if (prop === 'value' || prop === 'textContent' || prop === 'innerHTML') return '';
			if (prop === 'style' || prop === 'dataset' || prop === 'classList') return makeRecordingEl(texts);
			return () => makeRecordingEl(texts);
		},
		set: () => true,
		apply: () => makeRecordingEl(texts),
	}) as unknown as HTMLElement;
}

function makeFlow(
	app: unknown,
	opts: { globalRoot?: string; sourceFileName?: string; ontology?: string; data?: ParsedData } = {},
): { flow: ImportFlow; texts: string[]; close: jest.Mock } {
	const plugin = {
		settings: { ...DEFAULT_SETTINGS, defaultOutputPath: opts.globalRoot ?? SHARED_ROOT },
		debug: debugStub,
	} as unknown as ConstructorParameters<typeof ImportFlow>[1];
	const texts: string[] = [];
	const close = jest.fn();
	const flow = new ImportFlow(
		app as ConstructorParameters<typeof ImportFlow>[0],
		plugin,
		{ containerEl: makeRecordingEl(texts), close },
	);
	const data = opts.data ?? parsed();
	flow.sourceFile = { name: opts.sourceFileName ?? SOURCE_FILE } as File;
	flow.parsedData = data;
	flow.columnConfigs = new Map(COLUMN_CONFIGS);
	// The shipped path for a framework import is the shape workbench, and it is
	// the only path that carries a real ontology: the classic column-mapping path
	// has no place to put one and stamps every import 'unknown'.
	flow.workbench = new MappingWorkbench({
		parsedData: data,
		columnInfos: analyzeColumns(data),
		outputPath: opts.globalRoot ?? SHARED_ROOT,
		debug: debugStub,
		defaultPresetId: 'browsable-framework',
		sourceOntology: opts.ontology ?? ONTOLOGY,
		onChange: () => {},
	});
	return { flow, texts, close };
}

/** Where this flow says the import lands, after it has been allowed to look. */
async function askWhereItLands(
	app: unknown,
	opts?: Parameters<typeof makeFlow>[1],
): Promise<{ flow: ImportFlow; destination: string; prepared: { ok: boolean; changed: boolean } }> {
	const { flow } = makeFlow(app, opts);
	const prepared = await inner(flow).prepareStep3(true);
	return { flow, prepared, destination: inner(flow).currentOutputPath() };
}

// ---------------------------------------------------------------------------
// The audit the acceptance criterion is written in terms of.
// ---------------------------------------------------------------------------

/** curie -> every file claiming it. More than one entry is a duplicate identity. */
function curieOwners(files: Map<string, string>): Map<string, string[]> {
	const owners = new Map<string, string[]>();
	for (const [path, text] of files) {
		const fm = frontmatterOf(text);
		if (!fm._crosswalker || typeof fm.curie !== 'string') continue;
		const list = owners.get(fm.curie);
		if (list) list.push(path);
		else owners.set(fm.curie, [path]);
	}
	return owners;
}

function duplicateCuries(files: Map<string, string>): Array<[string, string[]]> {
	return [...curieOwners(files)].filter(([, paths]) => paths.length > 1);
}

function ambiguousIdentityErrors(result: GenerationResult): string[] {
	return result.errors.filter((e) => /Ambiguous identity/.test(e.message)).map((e) => e.message);
}

/** Every path the result reports back to the user, in one list. */
function reportedPaths(result: GenerationResult): string[] {
	return [
		...result.created,
		...result.skipped,
		...(result.moved ?? []).map((m) => m.to),
		...(result.orphans ?? []).map((o) => o.path),
	];
}

/** Every hub's curie in the vault, sorted. One entry per hub note. */
function hubCuriesOf(files: Map<string, string>): string[] {
	return [...files.values()]
		.filter((text) => frontmatterOf(text).kind === 'hub')
		.map((text) => String(frontmatterOf(text).curie))
		.sort();
}

function pathsOfKind(files: Map<string, string>, kind: string): string[] {
	return [...files]
		.filter(([, text]) => frontmatterOf(text).kind === kind)
		.map(([path]) => path)
		.sort();
}

/**
 * The same source with two rows the vault has never held. Under `skip` only the
 * rows a run CREATES enter the enrichment batch, so a scenario that needs the
 * enrichment phase to run at all has to add new rows -- and at least
 * `HUB_MIN_MEMBERS` of them, or no facet hub is materialized.
 */
function rowsPlusTwoNew(): ParsedData {
	return {
		columns: [...COLUMNS],
		rows: [
			...ROWS.map((r) => ({ ...r })),
			{ technique_id: 'T1666', name: 'A New Technique', tactic: 'Persistence', domain: 'Enterprise' },
			{ technique_id: 'T1667', name: 'Another New Technique', tactic: 'Persistence', domain: 'Enterprise' },
		],
		rowCount: ROWS.length + 2,
	};
}

/** The prose a user typed onto one hub, marked so it is unmistakable. */
const HUB_PROSE = 'Our team owns this tactic. Escalate to the on-call analyst.';
const HUB_WITH_PROSE = 'Ontologies/Persistence/Persistence.md';

// ===========================================================================
// 1. WHERE A REFRESH OF A PRE-FIX VAULT LANDS (A-1, A-2, A-3).
// ===========================================================================

describe('a refresh is offered the folder its own set already occupies', () => {
	it('reads the destination off the set, never off the source file name', async () => {
		// What the derived rule would say, spelled out so the failure this test
		// guards is legible: a folder the user's notes have never been in.
		const vault = await seedPreFixVault();
		expect(resolveDestinationDefault(SHARED_ROOT, SOURCE_FILE, null)).toBe(DERIVED_ROOT);

		const { destination, prepared } = await askWhereItLands(vault.app);
		expect(prepared.ok).toBe(true);
		expect(destination).toBe(SHARED_ROOT);
		expect(destination).not.toBe(DERIVED_ROOT);
	});

	it('adopts the same root when the source file was renamed since the first import', async () => {
		// The derived root is a function of the file name, and the file name is the
		// one thing a user is free to change between releases. Ownership is stamped,
		// so a rename cannot move an import.
		const vault = await seedPreFixVault();
		const { destination } = await askWhereItLands(vault.app, { sourceFileName: 'attack-mini-v2.csv' });
		expect(destination).toBe(SHARED_ROOT);
	});

	it('preselects refreshing exactly the set whose stamps this source carries', async () => {
		const vault = await seedPreFixVault();
		const { flow } = await askWhereItLands(vault.app);
		const sets = inner(flow).discoveredSets ?? [];
		expect(sets).toHaveLength(1);
		expect(inner(flow).importSetChoice).toEqual({ id: sets[0].id });
		expect(inner(flow).selectedImportSet()).toEqual({ id: sets[0].id });
	});

	it('matches on the two facts the write loop actually stamps', async () => {
		// A-2 replaced curie probing with stamped-fact matching, so the keys the
		// wizard derives and the keys generation writes must be the same strings.
		// Asserted against a real generated vault, never against a literal.
		const vault = await seedPreFixVault();
		const { flow } = await askWhereItLands(vault.app);
		const keys = inner(flow).sourceIdentityKeys();
		const [set] = inner(flow).discoveredSets ?? [];

		expect(keys).toEqual({ recipeId: `custom-${ONTOLOGY}`, ontologyPrefix: ONTOLOGY });
		expect(set.recipeIds).toContain(keys.recipeId);
		expect(set.ontologyPrefixes).toContain(keys.ontologyPrefix);
	});

	it('discovers the set wherever it lives, not only under the folder it would derive', async () => {
		// The circularity A-2 removed: discovery used to be scoped to the
		// destination, and the destination is what the ownership answer decides.
		// A set that sits nowhere near the derived root must still be found.
		const vault = await seedPreFixVault();
		const { flow } = await askWhereItLands(vault.app, { globalRoot: 'Reference/Compliance' });
		expect((inner(flow).discoveredSets ?? []).map((s) => s.root)).toEqual([SHARED_ROOT]);
		expect(inner(flow).currentOutputPath()).toBe(SHARED_ROOT);
	});
});

// ===========================================================================
// 2. THE ACCEPTANCE CRITERION (A-8), UNDER BOTH OVERWRITE MODES.
//
// CLOSED GAP -- `skip` mode, two clauses, formerly `it.failing`.
//
// Under `overwriteMode: 'skip'` every existing row returned from the write loop
// BEFORE `enrichRecords.push` (the skip `return` sat above the collection), so
// the enrichment batch was empty, `applyEnrichment` never ran, and no hub curie
// was ever added to `producedCuries`. Every hub the set owns was therefore
// reported as an orphan.
//
// AM-2 closed it: a row this run KEPT is still a row it vouches for, so a
// bookkeeping pass derives the hub identities the kept rows imply and marks
// them produced -- without writing, merging or relocating anything, which is
// why hub prose survives (asserted immediately after this section, byte for
// byte). Both clauses are ordinary `it` again. The reverse experiment lives in
// section 8: it now proves the absence, on a vault that was never de-migrated,
// so a regression cannot hide behind the legacy shape.
// ===========================================================================

describe.each(['replace', 'skip'] as const)('refreshing a pre-fix vault (overwriteMode %s)', (overwriteMode) => {
	async function refresh() {
		const vault = await seedPreFixVault();
		vault.files.set(HUB_WITH_PROSE, `${vault.files.get(HUB_WITH_PROSE)!}\n${HUB_PROSE}\n`);
		const before = new Map(vault.files);
		const { flow, destination } = await askWhereItLands(vault.app);
		const importSet = inner(flow).selectedImportSet();
		const result = await generateNotes(
			vault.app, parsed(), CONFIG, options(destination, overwriteMode, { importSet }),
		);
		return { vault, before, destination, result, flow };
	}

	it('writes into the folder the set already occupies', async () => {
		const { destination } = await refresh();
		expect(destination).toBe(SHARED_ROOT);
	});

	it('leaves no two files claiming one identity', async () => {
		const { vault } = await refresh();
		expect(duplicateCuries(vault.files)).toEqual([]);
	});

	it('raises no ambiguous-identity error', async () => {
		const { result } = await refresh();
		expect(ambiguousIdentityErrors(result)).toEqual([]);
		expect(result.errors).toEqual([]);
	});

	it('moves none of the user existing notes', async () => {
		const { vault, before, result } = await refresh();
		expect(result.moved ?? []).toEqual([]);
		// Not just "reported no moves": every note the user had is still where it was.
		for (const path of before.keys()) expect(vault.files.has(path)).toBe(true);
		expect(vault.rename).not.toHaveBeenCalled();
	});

	it('creates no second copy of the import', async () => {
		const { vault, before } = await refresh();
		expect([...vault.files.keys()].sort()).toEqual([...before.keys()].sort());
	});

	it('reports only paths that exist', async () => {
		const { vault, result } = await refresh();
		const missing = reportedPaths(result).filter((p) => !vault.files.has(p));
		expect(missing).toEqual([]);
	});

	it('keeps the prose the user typed onto a hub', async () => {
		const { vault } = await refresh();
		expect(vault.files.get(HUB_WITH_PROSE)).toContain(HUB_PROSE);
	});

	it('reports no new orphans', async () => {
		const { result } = await refresh();
		expect(result.orphans ?? []).toEqual([]);
	});

	it('leaves every hub holding exactly one identity, at the address it already had', async () => {
		const { vault } = await refresh();
		expect(pathsOfKind(vault.files, 'hub')).toEqual([
			'Ontologies/Discovery/Discovery.md',
			'Ontologies/Ontologies.md',
			'Ontologies/Persistence/Persistence.md',
		]);
		// One identity each, and no hub sharing one with another.
		expect(hubCuriesOf(vault.files)).toHaveLength(3);
		expect(new Set(hubCuriesOf(vault.files)).size).toBe(3);
	});

	// The two modes part company HERE, and only here, which is the whole of what
	// AM-2 changed. `replace` rewrites each hub and therefore restamps it into the
	// address-independent form. `skip` must reach the same ORPHAN answer while
	// rewriting nothing at all, so the legacy address-derived curies stay exactly
	// as the de-migration left them. Asserting "restamped" in both modes would be
	// asserting that skip rewrote a hub, which is the behaviour AM-2 forbids.
	if (overwriteMode === 'replace') {
		it('restamps each hub into the address-independent form', async () => {
			const { vault } = await refresh();
			expect(hubCuriesOf(vault.files)).toEqual([
				`${ONTOLOGY}:hub/_root`,
				`${ONTOLOGY}:hub/discovery`,
				`${ONTOLOGY}:hub/persistence`,
			]);
		});
	} else {
		it('restamps no hub: each keeps the legacy curie the vault already held', async () => {
			const { vault, before } = await refresh();
			expect(hubCuriesOf(vault.files)).toEqual(hubCuriesOf(before));
			// Spelled out, so the thing being preserved is legible: the legacy
			// address-derived form, which is what makes the zero-orphan result above
			// evidence that the bookkeeping marked the ALIAS and not just the
			// current-form curie it would have computed from the recipe.
			expect(hubCuriesOf(vault.files)).toEqual([
				`${ONTOLOGY}:hub/ontologies`,
				`${ONTOLOGY}:hub/ontologies/discovery`,
				`${ONTOLOGY}:hub/ontologies/persistence`,
			]);
		});

		it('rewrites no hub at all, byte for byte', async () => {
			// AM-2's bookkeeping pass runs `enrich()` for its curies and must consume
			// nothing else. A pass that quietly wrote its result back would still
			// report zero orphans while destroying the prose the user typed, which is
			// the failure the "keeps the prose" clause above would only half catch:
			// it looks for one marked sentence, this compares every byte.
			const { vault, before } = await refresh();
			for (const [path, text] of before) {
				if (frontmatterOf(text).kind !== 'hub') continue;
				expect(vault.files.get(path)).toBe(text);
			}
			// And not merely "the same content after a rewrite": no write was issued.
			const written = vault.modify.mock.calls.map((call) => (call[0] as { path: string }).path);
			expect(written.filter((path) => frontmatterOf(before.get(path) ?? '').kind === 'hub')).toEqual([]);
		});
	}
});

// ===========================================================================
// 3. A-8, COMPANION 1: a SECOND, UNRELATED framework in the same legacy vault.
//
// This is the clause the original defect broke in the other direction: the
// review screen preselected "refresh" for whichever single set happened to sit
// in the destination folder, so a second framework was attributed to the first
// and generation merged two ontologies into one import set.
// ===========================================================================

describe('a second, unrelated framework in the same legacy vault', () => {
	const SECOND_SOURCE = 'cis-controls-v8.csv';
	const SECOND_ONTOLOGY = 'cis-controls-v8';
	const SECOND_ROOT = 'Ontologies/cis-controls-v8';

	const SECOND_ROWS = [
		{ technique_id: 'CIS-1', name: 'Inventory of Assets', tactic: 'Inventory', domain: 'IG1' },
		{ technique_id: 'CIS-1.1', name: 'Asset Inventory Tool', tactic: 'Inventory', domain: 'IG1' },
		{ technique_id: 'CIS-2', name: 'Software Inventory', tactic: 'Inventory', domain: 'IG1' },
	];

	function secondData(): ParsedData {
		return { columns: [...COLUMNS], rows: SECOND_ROWS.map((r) => ({ ...r })), rowCount: SECOND_ROWS.length };
	}

	const SECOND_RECIPE: Recipe = {
		...RECIPE,
		recipe: `custom-${SECOND_ONTOLOGY}`,
		source: { ontology: SECOND_ONTOLOGY, levels: ['tactic', 'leaf'] },
	};

	async function importSecond() {
		const vault = await seedPreFixVault();
		const firstBefore = new Map(vault.files);
		const { flow } = await askWhereItLands(vault.app, {
			sourceFileName: SECOND_SOURCE,
			ontology: SECOND_ONTOLOGY,
			data: secondData(),
		});
		const destination = inner(flow).currentOutputPath();
		const importSet = inner(flow).selectedImportSet();
		const result = await generateNotes(vault.app, secondData(), CONFIG, {
			...options(destination, 'replace', { recipeOverride: SECOND_RECIPE, importSet }),
			sourceFileName: SECOND_SOURCE,
		});
		return { vault, firstBefore, flow, destination, importSet, result };
	}

	it('defaults to a NEW set rather than refreshing the set already in the vault', async () => {
		const { flow, importSet } = await importSecond();
		expect((inner(flow).discoveredSets ?? []).length).toBe(1);
		expect(inner(flow).importSetChoice).toBe('new');
		expect(importSet).toBe('new');
	});

	it('lands in its own derived root, not in the first framework folder', async () => {
		const { destination } = await importSecond();
		expect(destination).toBe(SECOND_ROOT);
		expect(destination).not.toBe(SHARED_ROOT);
	});

	it('mints its own import set instead of joining the first', async () => {
		const { vault } = await importSecond();
		const sets = await discoverImportSets(vault.app, undefined);
		expect(sets).toHaveLength(2);
		expect(sets.map((s) => s.root).sort()).toEqual([SECOND_ROOT, SHARED_ROOT].sort());
		// Neither set carries the other's ontology: the two imports stayed separate.
		const byRoot = new Map(sets.map((s) => [s.root, s]));
		expect(byRoot.get(SHARED_ROOT)!.ontologyPrefixes).toEqual([ONTOLOGY]);
		expect(byRoot.get(SECOND_ROOT)!.ontologyPrefixes).toEqual([SECOND_ONTOLOGY]);
	});

	it('leaves the first framework coverage untouched, note for note', async () => {
		const { vault, firstBefore, result } = await importSecond();
		expect(result.errors).toEqual([]);
		for (const [path, text] of firstBefore) {
			expect(vault.files.get(path)).toBe(text);
		}
		expect(duplicateCuries(vault.files)).toEqual([]);
		expect(result.moved ?? []).toEqual([]);
		expect(result.orphans ?? []).toEqual([]);
	});
});

// ===========================================================================
// 4. A-8, COMPANION 2: a COLD CACHE at step 3 blocks, and never generates.
//
// A null `getFileCache` means "Obsidian has not read this file yet", never
// "this file has no properties". Whole-vault discovery has no raw-frontmatter
// fallback, so a cold cache shows a vault with fewer sets than it has -- and
// the missing set is exactly the one this import would have refreshed.
// ===========================================================================

describe('a cold metadata cache at step 3', () => {
	async function coldFlow() {
		const vault = await seedPreFixVault();
		for (const path of vault.files.keys()) vault.coldPaths.add(path);
		forgetSeedWrites(vault);
		const { flow } = makeFlow(vault.app);
		const prepared = await inner(flow).prepareStep3(true);
		return { vault, flow, prepared };
	}

	it('refuses to settle an answer, and says why in words a user can act on', async () => {
		const { flow, prepared } = await coldFlow();
		expect(prepared.ok).toBe(false);
		expect(inner(flow).indexingBlocked).toBe(
			'Obsidian is still indexing your vault. Wait a moment and open the import again.',
		);
		expect(inner(flow).discoveredSets).toBeNull();
	});

	it('blocks the Next button off step 2', async () => {
		const { flow } = await coldFlow();
		flow.currentStep = 2;
		await expect(flow.validateCurrentStep()).resolves.toBe(false);
	});

	it('refuses to hand generation an ownership answer', async () => {
		const { flow } = await coldFlow();
		expect(() => inner(flow).selectedImportSet()).toThrow(/still indexing/);
		expect(inner(flow).validateImportSetSelection()).toBe(false);
	});

	it('writes nothing at all when Generate is pressed anyway', async () => {
		const { vault, flow } = await coldFlow();
		const before = new Map(vault.files);
		await flow.generate();
		expect(vault.create).not.toHaveBeenCalled();
		expect(vault.modify).not.toHaveBeenCalled();
		expect(vault.rename).not.toHaveBeenCalled();
		expect([...vault.files]).toEqual([...before]);
		// The distinction A-4 exists to preserve: the vault picture is REFUSED,
		// never emptied. An empty list would read as "this vault holds no imports",
		// which is how a cold cache mints a duplicate of a set it could not see.
		expect(inner(flow).discoveredSets).toBeNull();
	});

	it('retries once the cache is warm, rather than latching the refusal', async () => {
		// The refusal deliberately clears the settled marker: a user who waits and
		// presses Next again must get a fresh answer, not the cached "no".
		const { vault, flow } = await coldFlow();
		vault.coldPaths.clear();
		const again = await inner(flow).prepareStep3();
		expect(again.ok).toBe(true);
		expect(inner(flow).indexingBlocked).toBeNull();
		expect(inner(flow).currentOutputPath()).toBe(SHARED_ROOT);
	});
});

// ===========================================================================
// 5. A-3 AT THE WIZARD: segment-wise recovery, and failing closed.
//
// `recoverImportSetRoot` itself is unit-tested in tests/import-set.test.ts.
// What is asserted here is the CONSEQUENCE: which folder the refresh is offered,
// and what happens when the answer is null. A green helper test next to a caller
// that ignores it is exactly how the original defect survived.
// ===========================================================================

describe('two sets whose folder names share a prefix', () => {
	/** Two independent imports, in sibling folders one name is a prefix of. */
	async function twoSiblingSets() {
		const vault = makeVault();
		const mini: Recipe = {
			...RECIPE,
			recipe: 'custom-nist-mini',
			source: { ontology: 'nist-mini', levels: ['tactic', 'leaf'] },
		};
		const minimal: Recipe = {
			...RECIPE,
			recipe: 'custom-nist-minimal',
			source: { ontology: 'nist-minimal', levels: ['tactic', 'leaf'] },
		};
		await generateNotes(vault.app, parsed(), CONFIG, options('Frameworks/NIST-mini', 'replace', { recipeOverride: mini, importSet: 'new' }));
		await generateNotes(vault.app, parsed(), CONFIG, options('Frameworks/NIST-minimal', 'replace', { recipeOverride: minimal, importSet: 'new' }));
		return vault;
	}

	it('refreshes into its own folder, never into a merged character prefix', async () => {
		const vault = await twoSiblingSets();
		const { destination } = await askWhereItLands(vault.app, {
			globalRoot: 'Frameworks',
			sourceFileName: 'nist-mini.csv',
			ontology: 'nist-mini',
		});
		expect(destination).toBe('Frameworks/NIST-mini');
		// The falsifying answer a common-string-prefix implementation gives: a
		// folder NEITHER set lives in, which a refresh would fork the import into.
		expect(destination).not.toBe('Frameworks/NIST-min');
		expect(destination).not.toBe('Frameworks/NIST-minimal');
	});

	it('sends the sibling source to the sibling folder, from the same vault', async () => {
		const vault = await twoSiblingSets();
		const { destination } = await askWhereItLands(vault.app, {
			globalRoot: 'Frameworks',
			sourceFileName: 'nist-minimal.csv',
			ontology: 'nist-minimal',
		});
		expect(destination).toBe('Frameworks/NIST-minimal');
	});
});

describe('a set whose notes are spread across two top-level folders', () => {
	/** One note dragged out of the import root into an unrelated tree. */
	async function spreadSet() {
		const vault = await seedPreFixVault();
		const stray = [...vault.files.keys()].find((p) => p.endsWith('/T1078.md'))!;
		vault.files.set('Archive/T1078.md', vault.files.get(stray)!);
		vault.files.delete(stray);
		return vault;
	}

	it('recovers no root at all, rather than inventing one', async () => {
		const vault = await spreadSet();
		const { flow } = await askWhereItLands(vault.app);
		const [set] = inner(flow).discoveredSets ?? [];
		expect(set.root).toBeNull();
	});

	it('names the problem in words that tell the user what to do', async () => {
		const vault = await spreadSet();
		const { flow } = await askWhereItLands(vault.app);
		expect(inner(flow).refreshRootProblem()).toBe(
			'Crosswalker cannot tell where this framework lives. Its notes are spread across more than one folder. Import it as a new set, or move its notes into one folder first.',
		);
	});

	it('refuses to generate rather than writing into a guessed folder', async () => {
		const vault = await spreadSet();
		const { flow } = await askWhereItLands(vault.app);
		expect(() => inner(flow).selectedImportSet()).toThrow(/spread across more than one folder/);
		expect(inner(flow).validateImportSetSelection()).toBe(false);

		const before = new Map(vault.files);
		await flow.generate();
		expect([...vault.files]).toEqual([...before]);
	});
});

// ===========================================================================
// 6. A-6: the hardening that must hold whatever the destination rule decides.
// ===========================================================================

describe('a new set refuses to mint into a folder another set already owns', () => {
	/** A set that already occupies the per-import root this source derives. */
	async function occupiedDerivedRoot() {
		return seedVault(RECIPE, DERIVED_ROOT);
	}

	it('refuses, and offers the one action that resolves it', async () => {
		const vault = await occupiedDerivedRoot();
		// A source the stamps do NOT connect to that set (a re-derived ontology),
		// so the default is a new set -- landing on the occupied derived root.
		const { flow } = await askWhereItLands(vault.app, { ontology: 'attack-mini-v2' });
		expect(inner(flow).importSetChoice).toBe('new');
		expect(inner(flow).currentOutputPath()).toBe(DERIVED_ROOT);
		expect(inner(flow).newSetOccupancyProblem())
			.toMatch(/^Ontologies\/attack-mini already holds notes owned by import set iset-[a-z0-9]{6}\. Choose another folder for this import, or refresh that set instead\.$/);
	});

	it('blocks Generate instead of writing a second ontology into that folder', async () => {
		const vault = await occupiedDerivedRoot();
		const { flow } = await askWhereItLands(vault.app, { ontology: 'attack-mini-v2' });
		const before = new Map(vault.files);
		expect(inner(flow).validateImportSetSelection()).toBe(false);
		await flow.generate();
		expect([...vault.files]).toEqual([...before]);
	});

	it('does not block a second framework that lands beside the first', async () => {
		// The guard must be a collision check, not a "somebody else is in this
		// vault" check: a legacy flat set at Ontologies must not make every new
		// import under Ontologies impossible.
		const vault = await seedPreFixVault();
		const { flow } = await askWhereItLands(vault.app, {
			sourceFileName: 'cis-controls-v8.csv',
			ontology: 'cis-controls-v8',
		});
		expect(inner(flow).currentOutputPath()).toBe('Ontologies/cis-controls-v8');
		expect(inner(flow).newSetOccupancyProblem()).toBeNull();
	});
});

describe('a suppressed move under skip mode', () => {
	/**
	 * The only way to ask the engine for a move it must then suppress: point a
	 * refresh at a different root. Part A keeps a refresh out of this state, and
	 * the engine must not depend on the wizard for its own safety (E1/E2).
	 */
	async function skipIntoAMovedRoot(recipeOverride: Recipe = RECIPE, rows: ParsedData = parsed()) {
		const vault = await seedPreFixVault(recipeOverride);
		const before = new Map(vault.files);
		const result = await generateNotes(vault.app, rows, CONFIG, options(DERIVED_ROOT, 'skip', { recipeOverride }));
		return { vault, before, result };
	}

	it('reports the path that exists, never the path the move would have used', async () => {
		const { vault, result } = await skipIntoAMovedRoot();
		expect([...result.skipped].sort()).toEqual([
			'Ontologies/Discovery/T1590.md',
			'Ontologies/Discovery/T1595.002.md',
			'Ontologies/Discovery/T1595.md',
			'Ontologies/Persistence/T1078.001.md',
			'Ontologies/Persistence/T1078.md',
			'Ontologies/Persistence/T1098.md',
		]);
		// The whole point: a user following the report lands on a real note.
		for (const path of result.skipped) expect(vault.files.has(path)).toBe(true);
		for (const path of result.skipped) expect(path.startsWith(DERIVED_ROOT)).toBe(false);
	});

	it('moves nothing at all', async () => {
		const { vault, before, result } = await skipIntoAMovedRoot();
		expect(result.moved ?? []).toEqual([]);
		expect(vault.rename).not.toHaveBeenCalled();
		expect([...vault.files.keys()].sort()).toEqual([...before.keys()].sort());
	});

	it('leaves a facet hub where it is instead of relocating it', async () => {
		// A facet hub's curie is address-independent, so identity resolution finds
		// it wherever it sits and WANTS to relocate it (the `replace` run below is
		// the control that proves it does). Under skip it must not, and the
		// enrichment phase has to enforce that itself rather than relying on the
		// caller having chosen a destination that never asks for a move.
		//
		// Two new rows, not one: under skip only the rows this run CREATES reach
		// the enrichment batch, and a facet hub is materialized only at
		// HUB_MIN_MEMBERS (2). One new row silently emits no hub at all, and the
		// assertion below would then hold for the wrong reason.
		const { vault, result } = await skipIntoAMovedRoot(FACET_RECIPE, rowsPlusTwoNew());

		expect(vault.files.has(`${SHARED_ROOT}/Enterprise.md`)).toBe(true);
		expect(vault.files.has(`${DERIVED_ROOT}/Enterprise.md`)).toBe(false);
		expect((result.moved ?? []).map((m) => m.from)).not.toContain(`${SHARED_ROOT}/Enterprise.md`);
		expect(vault.rename).not.toHaveBeenCalled();
	});

	it('relocates that same facet hub under replace, which is the control', async () => {
		// Without this the test above proves nothing: a hub that was never going to
		// move is not evidence that a suppression worked.
		const vault = await seedPreFixVault(FACET_RECIPE);
		const result = await generateNotes(
			vault.app, rowsPlusTwoNew(), CONFIG,
			options(DERIVED_ROOT, 'replace', { recipeOverride: FACET_RECIPE }),
		);
		expect(vault.files.has(`${DERIVED_ROOT}/Enterprise.md`)).toBe(true);
		expect(vault.files.has(`${SHARED_ROOT}/Enterprise.md`)).toBe(false);
		expect((result.moved ?? []).map((m) => m.from)).toContain(`${SHARED_ROOT}/Enterprise.md`);
	});
});

// ===========================================================================
// 7. A-7: what the user is actually shown.
//
// `moved` and `orphans` were written by the engine and read by nothing, which
// made two acceptance clauses untestable and hid a real answer from the user.
// ===========================================================================

describe('the results screen', () => {
	function render(result: Parameters<ImportFlow['renderGenerationResults']>[0]) {
		const { flow, texts } = makeFlow({});
		flow.renderGenerationResults(result);
		return texts;
	}

	const clean = {
		success: true,
		created: ['Ontologies/Persistence/T1078.md'],
		skipped: [],
		errors: [],
	};

	it('states that nothing moved, rather than saying nothing at all', () => {
		const texts = render({ ...clean, moved: [], orphans: [] });
		expect(texts).toContain('📦 Moved: 0 notes. Nothing was relocated.');
	});

	it('lists what moved when something did', () => {
		const texts = render({
			...clean,
			moved: [{ curie: `${ONTOLOGY}:T1078`, from: 'Ontologies/T1078.md', to: 'Ontologies/Persistence/T1078.md' }],
		});
		expect(texts).toContain('📦 Moved: 1 note was relocated.');
		expect(texts).toContain('Ontologies/T1078.md → Ontologies/Persistence/T1078.md');
	});

	it('counts the notes the source no longer produces, and says they were kept', () => {
		const texts = render({
			...clean,
			orphans: [{ curie: `${ONTOLOGY}:T1099`, path: 'Ontologies/Persistence/T1099.md' }],
		});
		expect(texts).toContain('🕳️ Orphans: 1 note is no longer in the source. They were kept, not deleted.');
		expect(texts).toContain(`${ONTOLOGY}:T1099: Ontologies/Persistence/T1099.md`);
	});

	// SUPERSEDED, NOT SWEPT. This section used to pin `it.failing('states the
	// orphan count even when it is zero')`: the orphan line renders only when the
	// count is non-zero, so on the clean refresh A-8 describes the user was told
	// that nothing moved and nothing whatsoever about orphans.
	//
	// AM-3 answered it somewhere else on purpose. A clean refresh never draws this
	// screen at all -- it closes -- so a screen-level fix would have been a fix the
	// common case cannot see. The guarantee moved to the SUCCESS NOTICE, which
	// fires on every run and always states both numbers. Section 11 holds it, and
	// section 9 drives it end to end.
	//
	// What remains true here, and is asserted above, is that the MOVED line renders
	// at zero: this screen is drawn when something moved, orphaned, or errored, and
	// on an errors-only draw the moved zero is the only count in view.
	it('renders no orphan line when there is nothing to report', () => {
		const texts = render({ ...clean, moved: [], orphans: [] });
		expect(texts.filter((t) => /Orphans/.test(t))).toEqual([]);
		expect(texts).toContain('📦 Moved: 0 notes. Nothing was relocated.');
	});
});

// ===========================================================================
// 8. AM-2 AT ITS NARROWEST: the same claim with the legacy shape removed.
//
// This section was the isolating experiment that proved the skip-mode gap was
// NOT the per-import root work's doing -- it reproduced on a vault the current
// engine had generated moments earlier, never de-migrated, with overwriteMode
// as the only variable. It is kept, inverted, for the same reason: if AM-2's
// bookkeeping ever regresses, this fails on the simplest possible vault, and
// the failure cannot be blamed on the legacy shape or on a changed root.
// ===========================================================================

describe('a skip refresh accounts for the hubs its kept rows imply', () => {
	it('reports no orphans on a vault this engine generated moments earlier', async () => {
		// No de-migration, no destination change, no legacy curies. Every row is
		// skipped, so under the old behaviour the enrichment batch was empty and
		// all three hubs were reported gone.
		const vault = await seedVault();
		const result = await generateNotes(vault.app, parsed(), CONFIG, options(SHARED_ROOT, 'skip'));
		// The rows really were kept, so "no orphans" is not "nothing happened".
		expect(result.skipped).toHaveLength(ROWS.length);
		expect(result.created).toEqual([]);
		expect((result.orphans ?? []).map((o) => o.curie).sort()).toEqual([]);
	});

	it('marks the hub identities rather than declining to look', async () => {
		// The other way to report zero orphans is to give up: `markKeptHubsProduced`
		// returns false on failure and the caller then SUPPRESSES orphan reporting.
		// A suppressed report and a clean report both read as an empty list, so the
		// absence of the warning is what separates them.
		const vault = await seedVault();
		const result = await generateNotes(vault.app, parsed(), CONFIG, options(SHARED_ROOT, 'skip'));
		expect(result.warnings ?? []).toEqual([]);
		expect(result.errors).toEqual([]);
	});

	it('still reports a hub that genuinely has no members left', async () => {
		// The falsifying case for "zero orphans" as a blanket answer: a source that
		// dropped every Discovery row must still surface the Discovery hub. Kept-row
		// bookkeeping vouches for the rows this run SAW, never for the whole set.
		const vault = await seedVault();
		const persistenceOnly: ParsedData = {
			columns: [...COLUMNS],
			rows: ROWS.filter((r) => r.tactic === 'Persistence').map((r) => ({ ...r })),
			rowCount: 3,
		};
		const result = await generateNotes(vault.app, persistenceOnly, CONFIG, options(SHARED_ROOT, 'skip'));
		expect((result.orphans ?? []).map((o) => o.curie).sort()).toEqual([
			`${ONTOLOGY}:T1590`,
			`${ONTOLOGY}:T1595`,
			`${ONTOLOGY}:T1595.002`,
			`${ONTOLOGY}:hub/discovery`,
		]);
	});

	it('does the same on the native recipe path, which is a second write loop', async () => {
		// `generateNotes` and `generateFromRecipe` are two write loops carrying the
		// same early return for a skipped row. A fix applied to one is not a fix to
		// the other, and this engine has regressed exactly that way before -- which
		// is why the recipe path gets its own assertion rather than an assumption
		// that the shared helper covers it.
		const vault = await seedVault();
		const [set] = await discoverImportSets(vault.app, undefined);
		const result = await generateFromRecipe(vault.app, parsed(), RECIPE, {
			basePath: SHARED_ROOT,
			overwriteMode: 'skip',
			createFolders: true,
			importSet: { id: set.id },
			// The seed's identities came from the title column, so the recipe path
			// has to be pointed at the same one or it invents `row-N` curies and
			// orphans the whole set for an unrelated reason.
			curieLocalPart: (row: Record<string, unknown>) => String(row.technique_id),
			facetsForRow: (row: Record<string, unknown>) => [{ namespace: 'domain', value: String(row.domain) }],
		});
		expect(result.errors).toEqual([]);
		expect(result.skipped).toHaveLength(ROWS.length);
		expect(result.orphans ?? []).toEqual([]);
	});

	it('does not orphan them under replace either, which is the control', async () => {
		const vault = await seedVault();
		const result = await generateNotes(vault.app, parsed(), CONFIG, options(SHARED_ROOT, 'replace'));
		expect(result.orphans ?? []).toEqual([]);
	});
});

// ===========================================================================
// 9. THE SAME CRITERION, DRIVEN THROUGH THE REAL WIZARD PATH.
//
// Sections 1-8 call `generateNotes` directly, which is precise but leaves one
// question open: does the flow that a user actually drives hand the engine the
// destination and the ownership answer the review screen showed them? Here the
// pre-fix vault is built by RUNNING THE WIZARD, so the refresh cannot differ
// from the original import in any way except the one under test, and the
// refresh is `flow.generate()` -- config, recipe, destination, ownership and
// overwrite mode all resolved by the flow itself.
//
// It also reaches the two clauses nothing else can: what the user is SHOWN when
// the refresh finishes, and that the refresh survives the wizard's own choice of
// destination and ownership rather than a hand-passed one.
//
// A-8 RESTATED (2026-08-30) asks for this end to end in BOTH overwrite modes,
// not just `replace`. Under `skip` the second run creates nothing at all, which
// is precisely the run that used to orphan every hub, so it is the mode where an
// end-to-end check has the most to say.
// ===========================================================================

describe.each(['replace', 'skip'] as const)('two real wizard runs, the second a refresh (overwriteMode %s)', (overwriteMode) => {
	/**
	 * Run the wizard once into the bare shared root -- which is exactly how the
	 * pre-fix vaults arose, the destination field having been seeded with the
	 * global output path -- then rewrite the result into the pre-fix on-disk
	 * shape and hand the vault to a second, untouched flow.
	 */
	async function firstImportThenRefresh() {
		const vault = makeVault();

		const first = makeFlow(vault.app);
		(first.flow as unknown as { destinationEdited: boolean }).destinationEdited = true;
		first.flow.outputPath = SHARED_ROOT;
		first.flow.overwriteMode = 'replace';
		first.flow.currentStep = 4;
		await inner(first.flow).prepareStep3(true);
		await first.flow.generate();

		deMigrateToPreFix(vault.files, SHARED_ROOT);
		vault.files.set(
			`${SHARED_ROOT}/Persistence.md`,
			`${vault.files.get(`${SHARED_ROOT}/Persistence.md`)!}\n${HUB_PROSE}\n`,
		);
		const before = new Map(vault.files);
		forgetSeedWrites(vault);

		const second = makeFlow(vault.app);
		second.flow.overwriteMode = overwriteMode;
		second.flow.currentStep = 4;
		await inner(second.flow).prepareStep3(true);
		const destination = inner(second.flow).currentOutputPath();
		// Only the refresh's notices, so the first import's cannot be mistaken for
		// the report the user reads at the end of the run under test.
		notices.length = 0;
		await second.flow.generate();

		return { vault, before, destination, second };
	}

	it('leaves the first import flat, with its concept notes AND its hubs at the bare root', async () => {
		// The starting state the whole criterion is about. Asserted rather than
		// assumed: a fixture that quietly nested itself would test nothing.
		const { before } = await firstImportThenRefresh();
		expect([...before.keys()].sort()).toEqual([
			'Ontologies/Discovery.md',
			'Ontologies/Ontologies.md',
			'Ontologies/Persistence.md',
			'Ontologies/T1078.md',
			'Ontologies/T1078/T1078.001.md',
			'Ontologies/T1098.md',
			'Ontologies/T1590.md',
			'Ontologies/T1595.md',
			'Ontologies/T1595/T1595.002.md',
		]);
	});

	it('refreshes into that same bare root', async () => {
		const { destination } = await firstImportThenRefresh();
		expect(destination).toBe(SHARED_ROOT);
		expect(destination).not.toBe(DERIVED_ROOT);
	});

	it('leaves the vault holding exactly the notes it held before', async () => {
		const { vault, before } = await firstImportThenRefresh();
		expect([...vault.files.keys()].sort()).toEqual([...before.keys()].sort());
		expect(duplicateCuries(vault.files)).toEqual([]);
		expect(vault.rename).not.toHaveBeenCalled();
	});

	it('keeps the prose the user typed onto a hub', async () => {
		const { vault } = await firstImportThenRefresh();
		expect(vault.files.get(`${SHARED_ROOT}/Persistence.md`)).toContain(HUB_PROSE);
	});

	it('raises no ambiguous-identity error, in the only place the user would see one', async () => {
		// End to end there is no `GenerationResult` to inspect: what the run
		// concluded reaches the user as a notice, or not at all. AM-4 makes an error
		// draw the results screen, so a clean close IS the assertion that none was
		// raised -- and the notice is checked too, because "closed quietly" was
		// exactly the old failure.
		const { second } = await firstImportThenRefresh();
		expect(noticeText()).not.toMatch(/Ambiguous identity|finished with \d+ errors/);
		expect(second.texts.filter((t) => /Ambiguous identity/.test(t))).toEqual([]);
	});

	// AM-3. This was `it.failing('tells the user that nothing moved')`: the results
	// screen draws only when something moved, orphaned or (now) errored, so on the
	// A-8 scenario itself -- a refresh that correctly moves nothing -- the user was
	// told nothing at all and could not tell "nothing moved" from "nobody checked".
	// The counts moved onto the success notice, which fires on every run, including
	// the one that closes.
	it('tells the user that nothing moved and nothing was orphaned', async () => {
		const { second } = await firstImportThenRefresh();
		expect(noticeText()).toContain('Nothing moved. No orphans.');
		// Still closes: AM-3 deliberately did NOT force a screen onto a clean run.
		expect(second.close).toHaveBeenCalledTimes(1);
		expect(second.texts.filter((t) => /Moved|Orphans/.test(t))).toEqual([]);
	});

	it('reports the run it actually did, rather than a fixed sentence', async () => {
		// The counts must be read off the result, not printed unconditionally. The
		// two modes take different branches through the write loop -- `replace`
		// rewrites all six notes, `skip` keeps all six -- and the notice has to
		// describe the one that happened.
		const { second } = await firstImportThenRefresh();
		void second;
		expect(noticeText()).toMatch(
			overwriteMode === 'replace'
				? /✅ Created 6 notes in [\d.]+s\. Nothing moved\. No orphans\./
				: /✅ Created 0 notes, skipped 6 existing in [\d.]+s\. Nothing moved\. No orphans\./,
		);
	});
});

// ===========================================================================
// 10. AM-1: A PLACEHOLDER IS NEVER AN IDENTITY.
//
// The classic column-mapping path is the DEFAULT install: `enableShapeWorkbench`
// is off, so most users never reach the shape workbench, and the classic path
// has nowhere to put an ontology. It stamped every import it ever ran
// `ontology: unknown`, `recipe: legacy-config`.
//
// A-2 then matched a source against a set on those two stamped facts -- which,
// for the default path, meant matching a placeholder against a placeholder.
// Every classic import paired with every other one, so the SECOND framework a
// user imported was attributed to the FIRST: the original misattribution bug
// arriving again through the door A-2 had just closed on the folder-scoped one.
//
// AM-1 answers on both sides -- matching never considers a sentinel, and the
// classic path stamps a real ontology going forward (the source file stem, a
// fact the source actually carries). The two halves are falsified separately
// below, because either one alone leaves a live failure.
// ===========================================================================

describe('the classic import path, which carries no ontology of its own', () => {
	const FIRST_SOURCE = 'attack-mini.csv';
	const SECOND_SOURCE = 'cis-controls-v8.csv';

	const CIS_ROWS = [
		{ technique_id: 'CIS-1', name: 'Inventory of Assets', tactic: 'Inventory', domain: 'IG1' },
		{ technique_id: 'CIS-1.1', name: 'Asset Inventory Tool', tactic: 'Inventory', domain: 'IG1' },
		{ technique_id: 'CIS-2', name: 'Software Inventory', tactic: 'Inventory', domain: 'IG1' },
	];

	function cisData(): ParsedData {
		return { columns: [...COLUMNS], rows: CIS_ROWS.map((r) => ({ ...r })), rowCount: CIS_ROWS.length };
	}

	/**
	 * A flow on the CLASSIC path. The single difference from `makeFlow` is the one
	 * that matters: no workbench is constructed, so `isWorkbenchMode()` is false
	 * and the flow goes through `legacyConfigToRecipe`. That is the shipped
	 * default, and the only path that mints the sentinels.
	 */
	function makeClassicFlow(
		app: unknown,
		opts: { sourceFileName: string; data?: ParsedData; globalRoot?: string },
	): { flow: ImportFlow; texts: string[]; close: jest.Mock } {
		const plugin = {
			settings: {
				...DEFAULT_SETTINGS,
				defaultOutputPath: opts.globalRoot ?? SHARED_ROOT,
				enableShapeWorkbench: false,
			},
			debug: debugStub,
		} as unknown as ConstructorParameters<typeof ImportFlow>[1];
		const texts: string[] = [];
		const close = jest.fn();
		const flow = new ImportFlow(
			app as ConstructorParameters<typeof ImportFlow>[0],
			plugin,
			{ containerEl: makeRecordingEl(texts), close },
		);
		flow.sourceFile = { name: opts.sourceFileName } as File;
		flow.parsedData = opts.data ?? parsed();
		flow.columnConfigs = new Map(COLUMN_CONFIGS);
		return { flow, texts, close };
	}

	/** What the review screen decided, before anything is written. */
	async function classicReview(app: unknown, opts: Parameters<typeof makeClassicFlow>[1]) {
		const { flow } = makeClassicFlow(app, opts);
		await inner(flow).prepareStep3(true);
		return {
			flow,
			choice: inner(flow).importSetChoice,
			destination: inner(flow).currentOutputPath(),
			keys: inner(flow).sourceIdentityKeys(),
		};
	}

	/** A whole classic import, driven by the flow itself. */
	async function classicImport(app: unknown, opts: Parameters<typeof makeClassicFlow>[1]) {
		const { flow, texts, close } = makeClassicFlow(app, opts);
		flow.overwriteMode = 'replace';
		flow.currentStep = 4;
		await inner(flow).prepareStep3(true);
		const choice = inner(flow).importSetChoice;
		const destination = inner(flow).currentOutputPath();
		await flow.generate();
		return { flow, texts, close, choice, destination };
	}

	it('stamps the source file stem as the ontology, not the placeholder', async () => {
		const vault = makeVault();
		await classicImport(vault.app, { sourceFileName: FIRST_SOURCE });
		const sets = await discoverImportSets(vault.app, undefined);
		expect(sets).toHaveLength(1);
		expect(sets[0].ontologyPrefixes).toEqual(['attack-mini']);
		expect(sets[0].ontologyPrefixes).not.toContain(LEGACY_ONTOLOGY_SENTINEL);
	});

	it('compares the same two strings the write loop stamps', async () => {
		// The keys the review screen matches on and the keys generation writes are
		// two independent derivations. Asserted against a REAL generated vault, so a
		// drift between them shows up here instead of as a silent non-match.
		const vault = makeVault();
		await classicImport(vault.app, { sourceFileName: FIRST_SOURCE });
		const { keys } = await classicReview(vault.app, { sourceFileName: FIRST_SOURCE });
		const [set] = await discoverImportSets(vault.app, undefined);

		expect(keys).toEqual({ recipeId: LEGACY_RECIPE_ID_SENTINEL, ontologyPrefix: 'attack-mini' });
		// The recipe-id sentinel really IS stamped on both sides. That is exactly
		// why honouring it as a fact matches everything, and why it is excluded.
		expect(set.recipeIds).toEqual([LEGACY_RECIPE_ID_SENTINEL]);
		expect(set.ontologyPrefixes).toContain(keys.ontologyPrefix);
	});

	it('defaults the SECOND framework to a new set instead of the first one', async () => {
		// The headline. Two unrelated classic sources, one vault. Both stamp the
		// recipe-id sentinel, so a membership test that honours it pairs them.
		const vault = makeVault();
		await classicImport(vault.app, { sourceFileName: FIRST_SOURCE });
		const firstFiles = new Map(vault.files);

		const second = await classicImport(vault.app, { sourceFileName: SECOND_SOURCE, data: cisData() });

		expect(second.choice).toBe('new');
		expect(second.destination).toBe('Ontologies/cis-controls-v8');
		// The consequence, not just the decision: two sets, and the first framework
		// is untouched, byte for byte.
		const sets = await discoverImportSets(vault.app, undefined);
		expect(sets).toHaveLength(2);
		expect(sets.map((s) => s.ontologyPrefixes.join(',')).sort()).toEqual(['attack-mini', 'cis-controls-v8']);
		for (const [path, text] of firstFiles) expect(vault.files.get(path)).toBe(text);
	});

	it('still refreshes its OWN set when the same source comes back', async () => {
		// The other half, and the reason the stem is stamped at all. With both values
		// sentinels there is nothing left to match on, so every re-import of the same
		// classic source would mint a second set beside the first.
		const vault = makeVault();
		const first = await classicImport(vault.app, { sourceFileName: FIRST_SOURCE });
		const [set] = await discoverImportSets(vault.app, undefined);

		const again = await classicReview(vault.app, { sourceFileName: FIRST_SOURCE });
		expect(again.choice).toEqual({ id: set.id });
		expect(again.destination).toBe(first.destination);
	});

	it('never auto-matches a legacy set stamped with the placeholder', async () => {
		// A vault imported BEFORE AM-1: no source name reached the shim, so the
		// ontology on disk is the sentinel. AM-1 says such a set never auto-matches,
		// and the awkward case is a source whose own stem IS the sentinel word: the
		// one input that could smuggle the placeholder back in as a fact.
		const vault = makeVault();
		await generateNotes(vault.app, parsed(), CONFIG, {
			basePath: SHARED_ROOT,
			overwriteMode: 'replace',
			createFolders: true,
			importSet: 'new',
		});
		const [legacy] = await discoverImportSets(vault.app, undefined);
		expect(legacy.ontologyPrefixes).toEqual([LEGACY_ONTOLOGY_SENTINEL]);

		const review = await classicReview(vault.app, { sourceFileName: `${LEGACY_ONTOLOGY_SENTINEL}.csv` });
		expect(review.keys.ontologyPrefix).toBe(LEGACY_ONTOLOGY_SENTINEL);
		// Both keys are placeholders on both sides, and the answer is still "new": a
		// set this import owns nothing of, which is the safe answer. The user can
		// still choose refresh explicitly.
		expect(review.choice).toBe('new');
	});
});

// ===========================================================================
// 11. AM-3: THE COUNTS RIDE ON THE SUCCESS NOTICE.
//
// The results screen draws only when something moved, orphaned or errored. A
// clean refresh -- the exact run A-8 is written about -- closes the wizard, so a
// screen-only report is a report the common case never sees, and "nothing moved"
// stays indistinguishable from "nobody checked".
//
// The notice fires on EVERY successful run and always states both numbers.
// ===========================================================================

describe('the success notice', () => {
	/** One wizard import into the shared root, then a second flow refreshing it. */
	async function importThenRefreshWith(rows: ParsedData) {
		const vault = makeVault();
		const first = makeFlow(vault.app);
		(first.flow as unknown as { destinationEdited: boolean }).destinationEdited = true;
		first.flow.outputPath = SHARED_ROOT;
		first.flow.overwriteMode = 'replace';
		first.flow.currentStep = 4;
		await inner(first.flow).prepareStep3(true);
		await first.flow.generate();

		const second = makeFlow(vault.app, { data: rows });
		second.flow.overwriteMode = 'replace';
		second.flow.currentStep = 4;
		await inner(second.flow).prepareStep3(true);
		notices.length = 0;
		await second.flow.generate();
		return { vault, second };
	}

	/** The same source minus one leaf row, so the refresh leaves one note behind. */
	function rowsMinusOne(): ParsedData {
		const rows = ROWS.filter((r) => r.technique_id !== 'T1590').map((r) => ({ ...r }));
		return { columns: [...COLUMNS], rows, rowCount: rows.length };
	}

	it('states both numbers on a clean run, and closes', async () => {
		const { second } = await importThenRefreshWith(parsed());
		expect(noticeText()).toContain('Nothing moved. No orphans.');
		expect(noticeText()).not.toContain('See results.');
		expect(second.close).toHaveBeenCalledTimes(1);
	});

	it('states the counts it actually found, and points at the screen', async () => {
		// The falsifying control for the test above: a notice that printed "Nothing
		// moved. No orphans." unconditionally would pass that one and fail here.
		const { second } = await importThenRefreshWith(rowsMinusOne());
		expect(noticeText()).toContain('0 moved, 1 orphans. See results.');
		expect(noticeText()).not.toContain('Nothing moved. No orphans.');
		// And the screen it points at really is drawn, with the orphan on it.
		expect(second.close).not.toHaveBeenCalled();
		expect(second.texts).toContain('🕳️ Orphans: 1 note is no longer in the source. They were kept, not deleted.');
	});

	it('carries the counts alongside the created and skipped totals, not instead of them', async () => {
		const { second } = await importThenRefreshWith(parsed());
		void second;
		expect(noticeText()).toMatch(/^✅ Created 6 notes in [\d.]+s\. Nothing moved\. No orphans\.$/m);
	});
});

// ===========================================================================
// 12. AM-4: AN IDENTITY COLLISION IS SHOWN, NEVER SWALLOWED.
//
// `Ambiguous identity` is raised at row 0 from the identity index, and it leaves
// `result.success` true. The wizard closed on any successful run that had not
// moved or orphaned anything, so the one surface that ever displayed the error
// was skipped and the window shut on it. Same family as the purge that reported
// success.
//
// It is also the clause A-8 restated added: no ambiguous-identity error, AND if
// one occurs it is displayed.
// ===========================================================================

describe('an identity collision on a run that would otherwise close', () => {
	/** One wizard import, optionally a duplicated concept note, then a refresh. */
	async function refreshOverACollision(duplicate: boolean) {
		const vault = makeVault();
		const first = makeFlow(vault.app);
		(first.flow as unknown as { destinationEdited: boolean }).destinationEdited = true;
		first.flow.outputPath = SHARED_ROOT;
		first.flow.overwriteMode = 'replace';
		first.flow.currentStep = 4;
		await inner(first.flow).prepareStep3(true);
		await first.flow.generate();

		let victim: string | null = null;
		if (duplicate) {
			// A second file claiming one concept identity: what a pre-fix double
			// import left behind, and the state A-8 says must be SHOWN.
			victim = [...vault.files].find(([, text]) => {
				const fm = frontmatterOf(text);
				return !!fm._crosswalker && fm.kind !== 'hub';
			})![0];
			vault.files.set(`${SHARED_ROOT}/Copy of ${victim.split('/').pop()}`, vault.files.get(victim)!);
			expect(duplicateCuries(vault.files)).toHaveLength(1);
		}

		const second = makeFlow(vault.app);
		second.flow.overwriteMode = 'replace';
		second.flow.currentStep = 4;
		await inner(second.flow).prepareStep3(true);
		notices.length = 0;
		await second.flow.generate();
		return { vault, second, victim };
	}

	it('does not close the window on it', async () => {
		const { second } = await refreshOverACollision(true);
		expect(second.close).not.toHaveBeenCalled();
	});

	it('draws the results screen, with the collision named on it', async () => {
		const { second, victim } = await refreshOverACollision(true);
		expect(second.texts).toContain('❌ Errors: 1');
		expect(second.texts).toContain('Errors');
		const collision = second.texts.filter((t) => /^Row 0: Ambiguous identity /.test(t));
		expect(collision).toHaveLength(1);
		// The message names both claimants, so the user can act on it.
		expect(collision[0]).toContain(victim!);
		expect(collision[0]).toContain('Copy of');
	});

	it('says so in the notice, instead of reporting an unqualified success', async () => {
		const { second } = await refreshOverACollision(true);
		void second;
		expect(noticeText()).toContain('Import finished with 1 errors. See results.');
	});

	it('closes on the same run without the collision, which is the control', async () => {
		// Without this, the three tests above prove only that the wizard draws a
		// screen, not that the COLLISION is what made it draw one.
		const { second } = await refreshOverACollision(false);
		expect(second.close).toHaveBeenCalledTimes(1);
		expect(second.texts.filter((t) => /Errors|Ambiguous/.test(t))).toEqual([]);
		expect(noticeText()).not.toContain('finished with');
	});
});
