/**
 * Debug logging utility for Crosswalker
 *
 * Writes logs to a debug.log file in the vault root for easy inspection.
 * Logs persist across plugin reloads and can be searched in Obsidian.
 */

import { App, TFile } from 'obsidian';

export class DebugLog {
	private app: App;
	private enabled: boolean;
	private logPath = 'crosswalker-debug.log';

	constructor(app: App, enabled: boolean = false) {
		this.app = app;
		this.enabled = enabled;
	}

	/**
	 * Enable or disable debug logging
	 */
	setEnabled(enabled: boolean): void {
		this.enabled = enabled;
	}

	/**
	 * Log a message with optional data
	 */
	async log(message: string, data?: any): Promise<void> {
		// Always log to console
		if (data) {
			console.log(`[Crosswalker] ${message}`, data);
		} else {
			console.log(`[Crosswalker] ${message}`);
		}

		// Only write to file if enabled
		if (!this.enabled) return;

		const timestamp = new Date().toISOString();
		let logLine = `[${timestamp}] ${message}`;
		if (data !== undefined) {
			logLine += '\n```json\n' + JSON.stringify(data, null, 2) + '\n```';
		}
		logLine += '\n\n---\n\n';

		try {
			await this.appendToLog(logLine);
		} catch (error) {
			console.error('[Crosswalker] Failed to write debug log:', error);
		}
	}

	/**
	 * Append content to the log file, creating it if needed.
	 * Handles race conditions by catching "file exists" errors.
	 */
	private async appendToLog(content: string): Promise<void> {
		const file = this.app.vault.getAbstractFileByPath(this.logPath);

		if (file instanceof TFile) {
			// File exists - append to it
			const existing = await this.app.vault.read(file);
			await this.app.vault.modify(file, existing + content);
		} else {
			// File doesn't exist - try to create it
			try {
				await this.app.vault.create(this.logPath, this.getHeader() + content);
			} catch (createError: any) {
				// If creation fails because file now exists (race condition),
				// try to append instead
				if (createError?.message?.includes('already exists')) {
					const newFile = this.app.vault.getAbstractFileByPath(this.logPath);
					if (newFile instanceof TFile) {
						const existing = await this.app.vault.read(newFile);
						await this.app.vault.modify(newFile, existing + content);
					}
				} else {
					throw createError;
				}
			}
		}
	}

	/**
	 * Log an error
	 */
	async error(message: string, error?: Error | any): Promise<void> {
		const errorData = error instanceof Error
			? { message: error.message, stack: error.stack }
			: error;
		await this.log(`ERROR: ${message}`, errorData);
	}

	/**
	 * Clear the debug log file
	 */
	async clear(): Promise<void> {
		try {
			const file = this.app.vault.getAbstractFileByPath(this.logPath);
			if (file instanceof TFile) {
				await this.app.vault.modify(file, this.getHeader());
			}
		} catch (error) {
			console.error('[Crosswalker] Failed to clear debug log:', error);
		}
	}

	/**
	 * Delete the debug log file
	 */
	async delete(): Promise<void> {
		try {
			const file = this.app.vault.getAbstractFileByPath(this.logPath);
			if (file instanceof TFile) {
				await this.app.vault.delete(file);
			}
		} catch (error) {
			console.error('[Crosswalker] Failed to delete debug log:', error);
		}
	}

	private getHeader(): string {
		return `# Crosswalker debug log

Created: ${new Date().toISOString()}

> This file is auto-generated by Crosswalker for debugging.
> Delete this file or disable debug logging in settings when done.

---

`;
	}
}
