#!/usr/bin/env bun
/**
 * codegen-types.ts — generate TypeScript types from spec/*.schema.json
 *
 * Run via `bun run codegen`. Outputs into src/types/generated/, which is
 * committed to git so reviewers can see the schema impact in PR diffs.
 *
 * Per the v0.1.1 milestone: spec/ schemas are the load-bearing contract;
 * the plugin code consumes typed structures generated from those schemas
 * rather than hand-maintained TS interfaces. When schemas change,
 * re-run this and commit the generated diff.
 */

import { compileFromFile } from 'json-schema-to-typescript';
import { mkdir, writeFile } from 'node:fs/promises';
import { resolve, join } from 'node:path';

const REPO_ROOT = resolve(__dirname, '..');
const SPEC_DIR = join(REPO_ROOT, 'spec');
const OUT_DIR = join(REPO_ROOT, 'src', 'types', 'generated');

const SPECS = [
	{ schema: 'tier1.schema.json', out: 'tier1.ts' },
	{ schema: 'recipe.schema.json', out: 'recipe.ts' },
];

async function main(): Promise<void> {
	await mkdir(OUT_DIR, { recursive: true });

	for (const { schema, out } of SPECS) {
		const inputPath = join(SPEC_DIR, schema);
		const outputPath = join(OUT_DIR, out);
		console.log(`  ${schema} → src/types/generated/${out}`);

		const ts = await compileFromFile(inputPath, {
			bannerComment: `/**\n * THIS FILE IS AUTO-GENERATED by tools/codegen-types.ts.\n * Source: spec/${schema}\n * Do NOT edit by hand. Re-run \`bun run codegen\` after schema changes.\n */`,
			style: { singleQuote: true, useTabs: true },
		});

		await writeFile(outputPath, ts);
	}

	console.log(`\nGenerated ${SPECS.length} files into src/types/generated/`);
}

main().catch((err) => {
	console.error('Code generation failed:', err);
	process.exit(1);
});
